// Shared word bank for pet training games
// English words with Vietnamese hints
const WORD_BANK = [
  // ── 3 letters ──
  { word: 'cat', hint: 'Con mèo' },
  { word: 'dog', hint: 'Con chó' },
  { word: 'sun', hint: 'Mặt trời' },
  { word: 'run', hint: 'Chạy' },
  { word: 'egg', hint: 'Quả trứng' },
  { word: 'red', hint: 'Màu đỏ' },
  { word: 'hat', hint: 'Cái mũ' },
  { word: 'cup', hint: 'Cái cốc' },
  { word: 'pen', hint: 'Cái bút' },
  { word: 'box', hint: 'Cái hộp' },
  { word: 'bag', hint: 'Cái túi' },
  { word: 'bus', hint: 'Xe buýt' },
  { word: 'car', hint: 'Xe ô tô' },
  { word: 'bed', hint: 'Cái giường' },
  { word: 'cow', hint: 'Con bò' },
  { word: 'pig', hint: 'Con lợn' },
  { word: 'ant', hint: 'Con kiến' },
  { word: 'bee', hint: 'Con ong' },
  { word: 'fly', hint: 'Con ruồi' },
  { word: 'map', hint: 'Bản đồ' },
  { word: 'ice', hint: 'Đá / Băng' },
  { word: 'sky', hint: 'Bầu trời' },
  { word: 'sea', hint: 'Biển' },
  { word: 'toy', hint: 'Đồ chơi' },
  { word: 'key', hint: 'Chìa khóa' },
  { word: 'ear', hint: 'Cái tai' },
  { word: 'eye', hint: 'Con mắt' },
  { word: 'leg', hint: 'Cái chân' },
  { word: 'arm', hint: 'Cánh tay' },
  { word: 'fan', hint: 'Cái quạt' },

  // ── 4 letters ──
  { word: 'book', hint: 'Quyển sách' },
  { word: 'fish', hint: 'Con cá' },
  { word: 'bird', hint: 'Con chim' },
  { word: 'tree', hint: 'Cái cây' },
  { word: 'rain', hint: 'Mưa' },
  { word: 'star', hint: 'Ngôi sao' },
  { word: 'cake', hint: 'Bánh' },
  { word: 'door', hint: 'Cái cửa' },
  { word: 'hand', hint: 'Bàn tay' },
  { word: 'moon', hint: 'Mặt trăng' },
  { word: 'frog', hint: 'Con ếch' },
  { word: 'duck', hint: 'Con vịt' },
  { word: 'bear', hint: 'Con gấu' },
  { word: 'deer', hint: 'Con hươu' },
  { word: 'lion', hint: 'Con sư tử' },
  { word: 'wolf', hint: 'Con sói' },
  { word: 'goat', hint: 'Con dê' },
  { word: 'lamp', hint: 'Cái đèn' },
  { word: 'ball', hint: 'Quả bóng' },
  { word: 'rice', hint: 'Gạo / Cơm' },
  { word: 'milk', hint: 'Sữa' },
  { word: 'soup', hint: 'Súp / Canh' },
  { word: 'meat', hint: 'Thịt' },
  { word: 'salt', hint: 'Muối' },
  { word: 'shoe', hint: 'Giày' },
  { word: 'sock', hint: 'Tất / Vớ' },
  { word: 'coat', hint: 'Áo khoác' },
  { word: 'ring', hint: 'Chiếc nhẫn' },
  { word: 'bell', hint: 'Cái chuông' },
  { word: 'drum', hint: 'Cái trống' },
  { word: 'flag', hint: 'Lá cờ' },
  { word: 'ship', hint: 'Con tàu' },
  { word: 'boat', hint: 'Chiếc thuyền' },
  { word: 'wind', hint: 'Gió' },
  { word: 'fire', hint: 'Lửa' },
  { word: 'snow', hint: 'Tuyết' },
  { word: 'sand', hint: 'Cát' },
  { word: 'gold', hint: 'Vàng' },
  { word: 'king', hint: 'Vua' },
  { word: 'nose', hint: 'Cái mũi' },
  { word: 'face', hint: 'Khuôn mặt' },
  { word: 'foot', hint: 'Bàn chân' },
  { word: 'hair', hint: 'Tóc' },
  { word: 'neck', hint: 'Cổ' },
  { word: 'blue', hint: 'Màu xanh dương' },
  { word: 'pink', hint: 'Màu hồng' },
  { word: 'gray', hint: 'Màu xám' },
  { word: 'love', hint: 'Tình yêu' },
  { word: 'sing', hint: 'Hát' },
  { word: 'jump', hint: 'Nhảy' },
  { word: 'swim', hint: 'Bơi' },
  { word: 'cook', hint: 'Nấu ăn' },
  { word: 'read', hint: 'Đọc' },
  { word: 'draw', hint: 'Vẽ' },
  { word: 'play', hint: 'Chơi' },
  { word: 'walk', hint: 'Đi bộ' },
  { word: 'talk', hint: 'Nói chuyện' },
  { word: 'gift', hint: 'Quà tặng' },
  { word: 'park', hint: 'Công viên' },
  { word: 'road', hint: 'Con đường' },
  { word: 'wall', hint: 'Bức tường' },
  { word: 'roof', hint: 'Mái nhà' },
  { word: 'farm', hint: 'Nông trại' },
  { word: 'lake', hint: 'Hồ nước' },
  { word: 'leaf', hint: 'Chiếc lá' },
  { word: 'seed', hint: 'Hạt giống' },
  { word: 'rose', hint: 'Hoa hồng' },
  { word: 'nest', hint: 'Tổ chim' },
  { word: 'tail', hint: 'Cái đuôi' },
  { word: 'wing', hint: 'Cánh (chim)' },
  { word: 'bone', hint: 'Xương' },
  { word: 'crab', hint: 'Con cua' },
  { word: 'worm', hint: 'Con sâu' },

  // ── 5 letters ──
  { word: 'apple', hint: 'Quả táo' },
  { word: 'house', hint: 'Ngôi nhà' },
  { word: 'water', hint: 'Nước' },
  { word: 'smile', hint: 'Nụ cười' },
  { word: 'table', hint: 'Cái bàn' },
  { word: 'chair', hint: 'Cái ghế' },
  { word: 'sleep', hint: 'Ngủ' },
  { word: 'happy', hint: 'Vui vẻ' },
  { word: 'music', hint: 'Âm nhạc' },
  { word: 'dance', hint: 'Nhảy múa' },
  { word: 'green', hint: 'Màu xanh lá' },
  { word: 'bread', hint: 'Bánh mì' },
  { word: 'tiger', hint: 'Con hổ' },
  { word: 'cloud', hint: 'Đám mây' },
  { word: 'light', hint: 'Ánh sáng' },
  { word: 'horse', hint: 'Con ngựa' },
  { word: 'mouse', hint: 'Con chuột' },
  { word: 'snake', hint: 'Con rắn' },
  { word: 'whale', hint: 'Cá voi' },
  { word: 'shark', hint: 'Cá mập' },
  { word: 'sheep', hint: 'Con cừu' },
  { word: 'eagle', hint: 'Đại bàng' },
  { word: 'camel', hint: 'Con lạc đà' },
  { word: 'panda', hint: 'Gấu trúc' },
  { word: 'grape', hint: 'Quả nho' },
  { word: 'lemon', hint: 'Quả chanh vàng' },
  { word: 'mango', hint: 'Quả xoài' },
  { word: 'peach', hint: 'Quả đào' },
  { word: 'melon', hint: 'Quả dưa' },
  { word: 'onion', hint: 'Củ hành' },
  { word: 'candy', hint: 'Kẹo' },
  { word: 'juice', hint: 'Nước ép' },
  { word: 'pizza', hint: 'Bánh pizza' },
  { word: 'salad', hint: 'Rau trộn' },
  { word: 'spoon', hint: 'Cái thìa' },
  { word: 'knife', hint: 'Con dao' },
  { word: 'plate', hint: 'Cái đĩa' },
  { word: 'glass', hint: 'Cái ly' },
  { word: 'clock', hint: 'Đồng hồ' },
  { word: 'phone', hint: 'Điện thoại' },
  { word: 'piano', hint: 'Đàn piano' },
  { word: 'radio', hint: 'Đài radio' },
  { word: 'brush', hint: 'Bàn chải' },
  { word: 'towel', hint: 'Khăn tắm' },
  { word: 'shirt', hint: 'Áo sơ mi' },
  { word: 'skirt', hint: 'Váy ngắn' },
  { word: 'dress', hint: 'Váy dài' },
  { word: 'pants', hint: 'Quần dài' },
  { word: 'scarf', hint: 'Khăn quàng' },
  { word: 'queen', hint: 'Nữ hoàng' },
  { word: 'angel', hint: 'Thiên thần' },
  { word: 'heart', hint: 'Trái tim' },
  { word: 'dream', hint: 'Giấc mơ' },
  { word: 'story', hint: 'Câu chuyện' },
  { word: 'color', hint: 'Màu sắc' },
  { word: 'black', hint: 'Màu đen' },
  { word: 'white', hint: 'Màu trắng' },
  { word: 'brown', hint: 'Màu nâu' },
  { word: 'mouth', hint: 'Miệng' },
  { word: 'teeth', hint: 'Răng' },
  { word: 'brain', hint: 'Bộ não' },
  { word: 'blood', hint: 'Máu' },
  { word: 'river', hint: 'Dòng sông' },
  { word: 'ocean', hint: 'Đại dương' },
  { word: 'earth', hint: 'Trái đất' },
  { word: 'stone', hint: 'Hòn đá' },
  { word: 'grass', hint: 'Cỏ' },
  { word: 'field', hint: 'Cánh đồng' },
  { word: 'beach', hint: 'Bãi biển' },
  { word: 'train', hint: 'Tàu hỏa' },
  { word: 'plane', hint: 'Máy bay' },
  { word: 'truck', hint: 'Xe tải' },
  { word: 'climb', hint: 'Leo trèo' },
  { word: 'catch', hint: 'Bắt' },
  { word: 'throw', hint: 'Ném' },
  { word: 'write', hint: 'Viết' },
  { word: 'think', hint: 'Suy nghĩ' },
  { word: 'speak', hint: 'Nói' },
  { word: 'laugh', hint: 'Cười' },
  { word: 'clean', hint: 'Sạch sẽ' },
  { word: 'quiet', hint: 'Yên lặng' },
  { word: 'brave', hint: 'Dũng cảm' },
  { word: 'smart', hint: 'Thông minh' },
  { word: 'angry', hint: 'Tức giận' },
  { word: 'tired', hint: 'Mệt mỏi' },
  { word: 'sweet', hint: 'Ngọt' },
  { word: 'salty', hint: 'Mặn' },
  { word: 'round', hint: 'Tròn' },
  { word: 'sharp', hint: 'Sắc / Nhọn' },
  { word: 'heavy', hint: 'Nặng' },
  { word: 'child', hint: 'Đứa trẻ' },
  { word: 'world', hint: 'Thế giới' },
  { word: 'night', hint: 'Ban đêm' },
  { word: 'lunch', hint: 'Bữa trưa' },
  { word: 'tower', hint: 'Tháp' },

  // ── 6 letters ──
  { word: 'flower', hint: 'Bông hoa' },
  { word: 'school', hint: 'Trường học' },
  { word: 'friend', hint: 'Bạn bè' },
  { word: 'family', hint: 'Gia đình' },
  { word: 'orange', hint: 'Quả cam' },
  { word: 'monkey', hint: 'Con khỉ' },
  { word: 'rabbit', hint: 'Con thỏ' },
  { word: 'mother', hint: 'Mẹ' },
  { word: 'father', hint: 'Bố' },
  { word: 'sister', hint: 'Chị/em gái' },
  { word: 'garden', hint: 'Khu vườn' },
  { word: 'winter', hint: 'Mùa đông' },
  { word: 'summer', hint: 'Mùa hè' },
  { word: 'banana', hint: 'Quả chuối' },
  { word: 'planet', hint: 'Hành tinh' },
  { word: 'parrot', hint: 'Con vẹt' },
  { word: 'turtle', hint: 'Con rùa' },
  { word: 'spider', hint: 'Con nhện' },
  { word: 'insect', hint: 'Côn trùng' },
  { word: 'kitten', hint: 'Mèo con' },
  { word: 'puppy', hint: 'Chó con' },
  { word: 'donkey', hint: 'Con lừa' },
  { word: 'pigeon', hint: 'Chim bồ câu' },
  { word: 'cherry', hint: 'Quả anh đào' },
  { word: 'potato', hint: 'Khoai tây' },
  { word: 'tomato', hint: 'Cà chua' },
  { word: 'carrot', hint: 'Cà rốt' },
  { word: 'pepper', hint: 'Ớt / Tiêu' },
  { word: 'cheese', hint: 'Phô mai' },
  { word: 'butter', hint: 'Bơ' },
  { word: 'coffee', hint: 'Cà phê' },
  { word: 'cookie', hint: 'Bánh quy' },
  { word: 'noodle', hint: 'Mì / Phở' },
  { word: 'dinner', hint: 'Bữa tối' },
  { word: 'bottle', hint: 'Chai / Lọ' },
  { word: 'basket', hint: 'Cái rổ' },
  { word: 'bucket', hint: 'Cái xô' },
  { word: 'mirror', hint: 'Gương' },
  { word: 'pillow', hint: 'Cái gối' },
  { word: 'window', hint: 'Cửa sổ' },
  { word: 'candle', hint: 'Cây nến' },
  { word: 'camera', hint: 'Máy ảnh' },
  { word: 'guitar', hint: 'Đàn ghi-ta' },
  { word: 'rocket', hint: 'Tên lửa' },
  { word: 'bridge', hint: 'Cây cầu' },
  { word: 'castle', hint: 'Lâu đài' },
  { word: 'temple', hint: 'Ngôi đền' },
  { word: 'market', hint: 'Chợ' },
  { word: 'street', hint: 'Đường phố' },
  { word: 'forest', hint: 'Rừng' },
  { word: 'island', hint: 'Hòn đảo' },
  { word: 'desert', hint: 'Sa mạc' },
  { word: 'spring', hint: 'Mùa xuân' },
  { word: 'autumn', hint: 'Mùa thu' },
  { word: 'people', hint: 'Mọi người' },
  { word: 'doctor', hint: 'Bác sĩ' },
  { word: 'police', hint: 'Cảnh sát' },
  { word: 'farmer', hint: 'Nông dân' },
  { word: 'singer', hint: 'Ca sĩ' },
  { word: 'driver', hint: 'Tài xế' },
  { word: 'jacket', hint: 'Áo khoác' },
  { word: 'sandal', hint: 'Dép' },
  { word: 'gloves', hint: 'Găng tay' },
  { word: 'tongue', hint: 'Cái lưỡi' },
  { word: 'finger', hint: 'Ngón tay' },
  { word: 'elbow', hint: 'Khuỷu tay' },
  { word: 'muscle', hint: 'Cơ bắp' },
  { word: 'silver', hint: 'Bạc' },
  { word: 'yellow', hint: 'Màu vàng' },
  { word: 'purple', hint: 'Màu tím' },
  { word: 'circle', hint: 'Hình tròn' },
  { word: 'square', hint: 'Hình vuông' },
  { word: 'number', hint: 'Con số' },
  { word: 'letter', hint: 'Chữ cái' },
  { word: 'pencil', hint: 'Bút chì' },
  { word: 'eraser', hint: 'Cục tẩy' },
  { word: 'listen', hint: 'Lắng nghe' },
  { word: 'travel', hint: 'Du lịch' },
  { word: 'flying', hint: 'Bay' },
  { word: 'frozen', hint: 'Đông lạnh' },
  { word: 'hungry', hint: 'Đói' },
  { word: 'thirst', hint: 'Khát' },
  { word: 'strong', hint: 'Mạnh mẽ' },
  { word: 'gentle', hint: 'Dịu dàng' },
  { word: 'scared', hint: 'Sợ hãi' },
  { word: 'cloudy', hint: 'Nhiều mây' },
  { word: 'snowy', hint: 'Có tuyết' },
  { word: 'stormy', hint: 'Bão' },
  { word: 'sunny', hint: 'Nắng' },
  { word: 'soccer', hint: 'Bóng đá' },
  { word: 'tennis', hint: 'Quần vợt' },
  { word: 'trophy', hint: 'Cúp / Giải' },

  // ── 7+ letters ──
  { word: 'kitchen', hint: 'Nhà bếp' },
  { word: 'teacher', hint: 'Giáo viên' },
  { word: 'picture', hint: 'Bức tranh' },
  { word: 'chicken', hint: 'Con gà' },
  { word: 'student', hint: 'Học sinh' },
  { word: 'rainbow', hint: 'Cầu vồng' },
  { word: 'morning', hint: 'Buổi sáng' },
  { word: 'evening', hint: 'Buổi tối' },
  { word: 'dolphin', hint: 'Cá heo' },
  { word: 'giraffe', hint: 'Hươu cao cổ' },
  { word: 'penguin', hint: 'Chim cánh cụt' },
  { word: 'octopus', hint: 'Bạch tuộc' },
  { word: 'lobster', hint: 'Tôm hùm' },
  { word: 'hamster', hint: 'Chuột hamster' },
  { word: 'panther', hint: 'Báo đen' },
  { word: 'buffalo', hint: 'Con trâu' },
  { word: 'sparrow', hint: 'Chim sẻ' },
  { word: 'peacock', hint: 'Con công' },
  { word: 'leopard', hint: 'Con báo' },
  { word: 'monster', hint: 'Quái vật' },
  { word: 'diamond', hint: 'Kim cương' },
  { word: 'volcano', hint: 'Núi lửa' },
  { word: 'weather', hint: 'Thời tiết' },
  { word: 'thunder', hint: 'Sấm sét' },
  { word: 'country', hint: 'Đất nước' },
  { word: 'village', hint: 'Ngôi làng' },
  { word: 'library', hint: 'Thư viện' },
  { word: 'airport', hint: 'Sân bay' },
  { word: 'stadium', hint: 'Sân vận động' },
  { word: 'hospital', hint: 'Bệnh viện' },
  { word: 'bedroom', hint: 'Phòng ngủ' },
  { word: 'bathroom', hint: 'Phòng tắm' },
  { word: 'umbrella', hint: 'Cái ô / Dù' },
  { word: 'backpack', hint: 'Ba lô' },
  { word: 'necklace', hint: 'Vòng cổ' },
  { word: 'bracelet', hint: 'Vòng tay' },
  { word: 'sandwich', hint: 'Bánh mì kẹp' },
  { word: 'pancake', hint: 'Bánh kếp' },
  { word: 'popcorn', hint: 'Bỏng ngô' },
  { word: 'pumpkin', hint: 'Bí ngô' },
  { word: 'cabbage', hint: 'Bắp cải' },
  { word: 'spinach', hint: 'Rau chân vịt' },
  { word: 'avocado', hint: 'Quả bơ' },
  { word: 'coconut', hint: 'Quả dừa' },
  { word: 'pineapple', hint: 'Quả dứa' },
  { word: 'blueberry', hint: 'Quả việt quất' },
  { word: 'strawberry', hint: 'Quả dâu tây' },
  { word: 'watermelon', hint: 'Quả dưa hấu' },
  { word: 'chocolate', hint: 'Sô cô la' },
  { word: 'spaghetti', hint: 'Mì Ý' },
  { word: 'hamburger', hint: 'Bánh hamburger' },
  { word: 'breakfast', hint: 'Bữa sáng' },
  { word: 'scissors', hint: 'Cái kéo' },
  { word: 'calendar', hint: 'Lịch' },
  { word: 'computer', hint: 'Máy tính' },
  { word: 'notebook', hint: 'Vở / Sổ tay' },
  { word: 'textbook', hint: 'Sách giáo khoa' },
  { word: 'magazine', hint: 'Tạp chí' },
  { word: 'birthday', hint: 'Sinh nhật' },
  { word: 'holiday', hint: 'Ngày lễ' },
  { word: 'weekend', hint: 'Cuối tuần' },
  { word: 'tonight', hint: 'Tối nay' },
  { word: 'sunlight', hint: 'Ánh nắng' },
  { word: 'moonlight', hint: 'Ánh trăng' },
  { word: 'mountain', hint: 'Ngọn núi' },
  { word: 'waterfall', hint: 'Thác nước' },
  { word: 'mushroom', hint: 'Nấm' },
  { word: 'treasure', hint: 'Kho báu' },
  { word: 'princess', hint: 'Công chúa' },
  { word: 'soldier', hint: 'Người lính' },
  { word: 'captain', hint: 'Thuyền trưởng' },
  { word: 'painter', hint: 'Họa sĩ' },
  { word: 'dentist', hint: 'Nha sĩ' },
  { word: 'fireman', hint: 'Lính cứu hỏa' },
  { word: 'brother', hint: 'Anh/em trai' },
  { word: 'grandma', hint: 'Bà' },
  { word: 'grandpa', hint: 'Ông' },
  { word: 'husband', hint: 'Chồng' },
  { word: 'neighbor', hint: 'Hàng xóm' },
  { word: 'shoulder', hint: 'Vai' },
  { word: 'stomach', hint: 'Bụng / Dạ dày' },
  { word: 'elephant', hint: 'Con voi' },
  { word: 'squirrel', hint: 'Con sóc' },
  { word: 'kangaroo', hint: 'Chuột túi' },
  { word: 'flamingo', hint: 'Hồng hạc' },
  { word: 'goldfish', hint: 'Cá vàng' },
  { word: 'starfish', hint: 'Sao biển' },
  { word: 'butterfly', hint: 'Con bướm' },
  { word: 'jellyfish', hint: 'Con sứa' },
  { word: 'crocodile', hint: 'Cá sấu' },
  { word: 'dragonfly', hint: 'Chuồn chuồn' },
  { word: 'sunflower', hint: 'Hoa hướng dương' },
  { word: 'classroom', hint: 'Lớp học' },
  { word: 'building', hint: 'Tòa nhà' },
  { word: 'playground', hint: 'Sân chơi' },
  { word: 'universe', hint: 'Vũ trụ' },
  { word: 'triangle', hint: 'Hình tam giác' },
  { word: 'rectangle', hint: 'Hình chữ nhật' },
  { word: 'question', hint: 'Câu hỏi' },
  { word: 'language', hint: 'Ngôn ngữ' },
  { word: 'alphabet', hint: 'Bảng chữ cái' },
  { word: 'painting', hint: 'Bức tranh' },
  { word: 'exercise', hint: 'Bài tập' },
  { word: 'swimming', hint: 'Bơi lội' },
  { word: 'running', hint: 'Chạy bộ' },
  { word: 'sleeping', hint: 'Đang ngủ' },
  { word: 'shopping', hint: 'Mua sắm' },
  { word: 'champion', hint: 'Nhà vô địch' },
  { word: 'dinosaur', hint: 'Khủng long' },
]

export default WORD_BANK
