// Shared word bank for pet training games
// English words with Vietnamese hints
const WORD_BANK = [
  // ── 3 letters ──
  { word: 'cat', hint: 'Con mèo' },
  { word: 'dog', hint: 'Con chó' },
  { word: 'sun', hint: 'Mặt trời' },
  { word: 'run', hint: 'Chạy' },
  { word: 'egg', hint: 'Quả trứng' },
  { word: 'red', hint: 'Màu đỏ' },
  { word: 'hat', hint: 'Cái mũ' },
  { word: 'cup', hint: 'Cái cốc' },
  { word: 'pen', hint: 'Cái bút' },
  { word: 'box', hint: 'Cái hộp' },
  { word: 'bag', hint: 'Cái túi' },
  { word: 'bus', hint: 'Xe buýt' },
  { word: 'car', hint: 'Xe ô tô' },
  { word: 'bed', hint: 'Cái giường' },
  { word: 'cow', hint: 'Con bò' },
  { word: 'pig', hint: 'Con lợn' },
  { word: 'ant', hint: 'Con kiến' },
  { word: 'bee', hint: 'Con ong' },
  { word: 'fly', hint: 'Con ruồi' },
  { word: 'map', hint: 'Bản đồ' },
  { word: 'ice', hint: 'Đá / Băng' },
  { word: 'sky', hint: 'Bầu trời' },
  { word: 'sea', hint: 'Biển' },
  { word: 'toy', hint: 'Đồ chơi' },
  { word: 'key', hint: 'Chìa khóa' },
  { word: 'ear', hint: 'Cái tai' },
  { word: 'eye', hint: 'Con mắt' },
  { word: 'leg', hint: 'Cái chân' },
  { word: 'arm', hint: 'Cánh tay' },
  { word: 'fan', hint: 'Cái quạt' },
  { word: 'fox', hint: 'Con cáo' },
  { word: 'owl', hint: 'Con cú' },
  { word: 'bat', hint: 'Con dơi' },
  { word: 'nut', hint: 'Hạt' },
  { word: 'pie', hint: 'Bánh nướng' },
  { word: 'pot', hint: 'Cái nồi' },
  { word: 'jar', hint: 'Cái lọ' },
  { word: 'net', hint: 'Cái lưới' },
  { word: 'log', hint: 'Khúc gỗ' },
  { word: 'mud', hint: 'Bùn' },
  { word: 'fur', hint: 'Lông thú' },
  { word: 'gem', hint: 'Viên ngọc' },
  { word: 'ink', hint: 'Mực' },
  { word: 'jam', hint: 'Mứt' },
  { word: 'jaw', hint: 'Hàm' },
  { word: 'lip', hint: 'Môi' },
  { word: 'rug', hint: 'Tấm thảm' },
  { word: 'tap', hint: 'Vòi nước' },
  { word: 'van', hint: 'Xe van' },
  { word: 'vet', hint: 'Bác sĩ thú y' },
  { word: 'web', hint: 'Mạng nhện' },
  { word: 'zip', hint: 'Khóa kéo' },
  { word: 'hop', hint: 'Nhảy lò cò' },
  { word: 'hug', hint: 'Ôm' },
  { word: 'mix', hint: 'Trộn' },
  { word: 'nap', hint: 'Giấc ngủ ngắn' },
  { word: 'sip', hint: 'Nhấp (nước)' },
  { word: 'dew', hint: 'Sương' },
  { word: 'fog', hint: 'Sương mù' },
  { word: 'oak', hint: 'Cây sồi' },
  { word: 'rib', hint: 'Xương sườn' },
  { word: 'row', hint: 'Hàng / Dãy' },
  { word: 'saw', hint: 'Cái cưa' },
  { word: 'fig', hint: 'Quả sung' },
  { word: 'yam', hint: 'Khoai mỡ' },
  { word: 'bow', hint: 'Cái cung' },
  { word: 'axe', hint: 'Cái rìu' },
  { word: 'fin', hint: 'Vây cá' },
  { word: 'gap', hint: 'Khoảng trống' },
  { word: 'hen', hint: 'Gà mái' },
  { word: 'ram', hint: 'Cừu đực' },
  { word: 'cub', hint: 'Thú con' },
  { word: 'dam', hint: 'Đập nước' },
  { word: 'bay', hint: 'Vịnh' },
  { word: 'hut', hint: 'Túp lều' },

  // ── 4 letters ──
  { word: 'book', hint: 'Quyển sách' },
  { word: 'fish', hint: 'Con cá' },
  { word: 'bird', hint: 'Con chim' },
  { word: 'tree', hint: 'Cái cây' },
  { word: 'rain', hint: 'Mưa' },
  { word: 'star', hint: 'Ngôi sao' },
  { word: 'cake', hint: 'Bánh' },
  { word: 'door', hint: 'Cái cửa' },
  { word: 'hand', hint: 'Bàn tay' },
  { word: 'moon', hint: 'Mặt trăng' },
  { word: 'frog', hint: 'Con ếch' },
  { word: 'duck', hint: 'Con vịt' },
  { word: 'bear', hint: 'Con gấu' },
  { word: 'deer', hint: 'Con hươu' },
  { word: 'lion', hint: 'Con sư tử' },
  { word: 'wolf', hint: 'Con sói' },
  { word: 'goat', hint: 'Con dê' },
  { word: 'lamp', hint: 'Cái đèn' },
  { word: 'ball', hint: 'Quả bóng' },
  { word: 'rice', hint: 'Gạo / Cơm' },
  { word: 'milk', hint: 'Sữa' },
  { word: 'soup', hint: 'Súp / Canh' },
  { word: 'meat', hint: 'Thịt' },
  { word: 'salt', hint: 'Muối' },
  { word: 'shoe', hint: 'Giày' },
  { word: 'sock', hint: 'Tất / Vớ' },
  { word: 'coat', hint: 'Áo khoác' },
  { word: 'ring', hint: 'Chiếc nhẫn' },
  { word: 'bell', hint: 'Cái chuông' },
  { word: 'drum', hint: 'Cái trống' },
  { word: 'flag', hint: 'Lá cờ' },
  { word: 'ship', hint: 'Con tàu' },
  { word: 'boat', hint: 'Chiếc thuyền' },
  { word: 'wind', hint: 'Gió' },
  { word: 'fire', hint: 'Lửa' },
  { word: 'snow', hint: 'Tuyết' },
  { word: 'sand', hint: 'Cát' },
  { word: 'gold', hint: 'Vàng' },
  { word: 'king', hint: 'Vua' },
  { word: 'nose', hint: 'Cái mũi' },
  { word: 'face', hint: 'Khuôn mặt' },
  { word: 'foot', hint: 'Bàn chân' },
  { word: 'hair', hint: 'Tóc' },
  { word: 'neck', hint: 'Cổ' },
  { word: 'blue', hint: 'Màu xanh dương' },
  { word: 'pink', hint: 'Màu hồng' },
  { word: 'gray', hint: 'Màu xám' },
  { word: 'love', hint: 'Tình yêu' },
  { word: 'sing', hint: 'Hát' },
  { word: 'jump', hint: 'Nhảy' },
  { word: 'swim', hint: 'Bơi' },
  { word: 'cook', hint: 'Nấu ăn' },
  { word: 'read', hint: 'Đọc' },
  { word: 'draw', hint: 'Vẽ' },
  { word: 'play', hint: 'Chơi' },
  { word: 'walk', hint: 'Đi bộ' },
  { word: 'talk', hint: 'Nói chuyện' },
  { word: 'gift', hint: 'Quà tặng' },
  { word: 'park', hint: 'Công viên' },
  { word: 'road', hint: 'Con đường' },
  { word: 'wall', hint: 'Bức tường' },
  { word: 'roof', hint: 'Mái nhà' },
  { word: 'farm', hint: 'Nông trại' },
  { word: 'lake', hint: 'Hồ nước' },
  { word: 'leaf', hint: 'Chiếc lá' },
  { word: 'seed', hint: 'Hạt giống' },
  { word: 'rose', hint: 'Hoa hồng' },
  { word: 'nest', hint: 'Tổ chim' },
  { word: 'tail', hint: 'Cái đuôi' },
  { word: 'wing', hint: 'Cánh (chim)' },
  { word: 'bone', hint: 'Xương' },
  { word: 'crab', hint: 'Con cua' },
  { word: 'worm', hint: 'Con sâu' },
  { word: 'bean', hint: 'Hạt đậu' },
  { word: 'cave', hint: 'Hang động' },
  { word: 'chef', hint: 'Đầu bếp' },
  { word: 'chin', hint: 'Cằm' },
  { word: 'clay', hint: 'Đất sét' },
  { word: 'club', hint: 'Câu lạc bộ' },
  { word: 'coal', hint: 'Than' },
  { word: 'coin', hint: 'Đồng xu' },
  { word: 'corn', hint: 'Ngô / Bắp' },
  { word: 'crow', hint: 'Con quạ' },
  { word: 'cube', hint: 'Hình lập phương' },
  { word: 'dive', hint: 'Lặn' },
  { word: 'dove', hint: 'Chim bồ câu' },
  { word: 'dusk', hint: 'Hoàng hôn' },
  { word: 'dust', hint: 'Bụi' },
  { word: 'ease', hint: 'Dễ dàng' },
  { word: 'fork', hint: 'Cái nĩa' },
  { word: 'frog', hint: 'Con ếch' },
  { word: 'fuel', hint: 'Nhiên liệu' },
  { word: 'gate', hint: 'Cổng' },
  { word: 'gear', hint: 'Bánh răng' },
  { word: 'glow', hint: 'Phát sáng' },
  { word: 'glue', hint: 'Keo dán' },
  { word: 'hare', hint: 'Thỏ rừng' },
  { word: 'hawk', hint: 'Chim ưng' },
  { word: 'heel', hint: 'Gót chân' },
  { word: 'hero', hint: 'Anh hùng' },
  { word: 'hill', hint: 'Ngọn đồi' },
  { word: 'hive', hint: 'Tổ ong' },
  { word: 'horn', hint: 'Sừng' },
  { word: 'iron', hint: 'Sắt' },
  { word: 'kite', hint: 'Con diều' },
  { word: 'knot', hint: 'Nút thắt' },
  { word: 'lime', hint: 'Quả chanh' },
  { word: 'nail', hint: 'Cái đinh' },
  { word: 'oven', hint: 'Lò nướng' },
  { word: 'pear', hint: 'Quả lê' },
  { word: 'pond', hint: 'Ao' },
  { word: 'quiz', hint: 'Câu đố' },
  { word: 'rope', hint: 'Dây thừng' },
  { word: 'ruby', hint: 'Hồng ngọc' },
  { word: 'sail', hint: 'Cánh buồm' },
  { word: 'silk', hint: 'Lụa' },
  { word: 'sink', hint: 'Bồn rửa' },
  { word: 'sofa', hint: 'Ghế sofa' },
  { word: 'swan', hint: 'Thiên nga' },
  { word: 'tomb', hint: 'Ngôi mộ' },
  { word: 'tray', hint: 'Cái khay' },
  { word: 'tuna', hint: 'Cá ngừ' },
  { word: 'vase', hint: 'Bình hoa' },
  { word: 'vest', hint: 'Áo ghi lê' },
  { word: 'vine', hint: 'Dây leo' },
  { word: 'wasp', hint: 'Con ong bắp cày' },
  { word: 'well', hint: 'Giếng nước' },
  { word: 'wick', hint: 'Bấc nến' },
  { word: 'yawn', hint: 'Ngáp' },
  { word: 'yoga', hint: 'Yoga' },
  { word: 'zone', hint: 'Khu vực' },
  { word: 'zoom', hint: 'Phóng to' },
  { word: 'reef', hint: 'Rạn san hô' },
  { word: 'seal', hint: 'Hải cẩu' },
  { word: 'surf', hint: 'Lướt sóng' },
  { word: 'trap', hint: 'Cái bẫy' },
  { word: 'wrap', hint: 'Gói / Bọc' },

  // ── 5 letters ──
  { word: 'apple', hint: 'Quả táo' },
  { word: 'house', hint: 'Ngôi nhà' },
  { word: 'water', hint: 'Nước' },
  { word: 'smile', hint: 'Nụ cười' },
  { word: 'table', hint: 'Cái bàn' },
  { word: 'chair', hint: 'Cái ghế' },
  { word: 'sleep', hint: 'Ngủ' },
  { word: 'happy', hint: 'Vui vẻ' },
  { word: 'music', hint: 'Âm nhạc' },
  { word: 'dance', hint: 'Nhảy múa' },
  { word: 'green', hint: 'Màu xanh lá' },
  { word: 'bread', hint: 'Bánh mì' },
  { word: 'tiger', hint: 'Con hổ' },
  { word: 'cloud', hint: 'Đám mây' },
  { word: 'light', hint: 'Ánh sáng' },
  { word: 'horse', hint: 'Con ngựa' },
  { word: 'mouse', hint: 'Con chuột' },
  { word: 'snake', hint: 'Con rắn' },
  { word: 'whale', hint: 'Cá voi' },
  { word: 'shark', hint: 'Cá mập' },
  { word: 'sheep', hint: 'Con cừu' },
  { word: 'eagle', hint: 'Đại bàng' },
  { word: 'camel', hint: 'Con lạc đà' },
  { word: 'panda', hint: 'Gấu trúc' },
  { word: 'grape', hint: 'Quả nho' },
  { word: 'lemon', hint: 'Quả chanh vàng' },
  { word: 'mango', hint: 'Quả xoài' },
  { word: 'peach', hint: 'Quả đào' },
  { word: 'melon', hint: 'Quả dưa' },
  { word: 'onion', hint: 'Củ hành' },
  { word: 'candy', hint: 'Kẹo' },
  { word: 'juice', hint: 'Nước ép' },
  { word: 'pizza', hint: 'Bánh pizza' },
  { word: 'salad', hint: 'Rau trộn' },
  { word: 'spoon', hint: 'Cái thìa' },
  { word: 'knife', hint: 'Con dao' },
  { word: 'plate', hint: 'Cái đĩa' },
  { word: 'glass', hint: 'Cái ly' },
  { word: 'clock', hint: 'Đồng hồ' },
  { word: 'phone', hint: 'Điện thoại' },
  { word: 'piano', hint: 'Đàn piano' },
  { word: 'radio', hint: 'Đài radio' },
  { word: 'brush', hint: 'Bàn chải' },
  { word: 'towel', hint: 'Khăn tắm' },
  { word: 'shirt', hint: 'Áo sơ mi' },
  { word: 'skirt', hint: 'Váy ngắn' },
  { word: 'dress', hint: 'Váy dài' },
  { word: 'pants', hint: 'Quần dài' },
  { word: 'scarf', hint: 'Khăn quàng' },
  { word: 'queen', hint: 'Nữ hoàng' },
  { word: 'angel', hint: 'Thiên thần' },
  { word: 'heart', hint: 'Trái tim' },
  { word: 'dream', hint: 'Giấc mơ' },
  { word: 'story', hint: 'Câu chuyện' },
  { word: 'color', hint: 'Màu sắc' },
  { word: 'black', hint: 'Màu đen' },
  { word: 'white', hint: 'Màu trắng' },
  { word: 'brown', hint: 'Màu nâu' },
  { word: 'mouth', hint: 'Miệng' },
  { word: 'teeth', hint: 'Răng' },
  { word: 'brain', hint: 'Bộ não' },
  { word: 'blood', hint: 'Máu' },
  { word: 'river', hint: 'Dòng sông' },
  { word: 'ocean', hint: 'Đại dương' },
  { word: 'earth', hint: 'Trái đất' },
  { word: 'stone', hint: 'Hòn đá' },
  { word: 'grass', hint: 'Cỏ' },
  { word: 'field', hint: 'Cánh đồng' },
  { word: 'beach', hint: 'Bãi biển' },
  { word: 'train', hint: 'Tàu hỏa' },
  { word: 'plane', hint: 'Máy bay' },
  { word: 'truck', hint: 'Xe tải' },
  { word: 'climb', hint: 'Leo trèo' },
  { word: 'catch', hint: 'Bắt' },
  { word: 'throw', hint: 'Ném' },
  { word: 'write', hint: 'Viết' },
  { word: 'think', hint: 'Suy nghĩ' },
  { word: 'speak', hint: 'Nói' },
  { word: 'laugh', hint: 'Cười' },
  { word: 'clean', hint: 'Sạch sẽ' },
  { word: 'quiet', hint: 'Yên lặng' },
  { word: 'brave', hint: 'Dũng cảm' },
  { word: 'smart', hint: 'Thông minh' },
  { word: 'angry', hint: 'Tức giận' },
  { word: 'tired', hint: 'Mệt mỏi' },
  { word: 'sweet', hint: 'Ngọt' },
  { word: 'salty', hint: 'Mặn' },
  { word: 'round', hint: 'Tròn' },
  { word: 'sharp', hint: 'Sắc / Nhọn' },
  { word: 'heavy', hint: 'Nặng' },
  { word: 'child', hint: 'Đứa trẻ' },
  { word: 'world', hint: 'Thế giới' },
  { word: 'night', hint: 'Ban đêm' },
  { word: 'lunch', hint: 'Bữa trưa' },
  { word: 'tower', hint: 'Tháp' },
  { word: 'alarm', hint: 'Báo thức' },
  { word: 'alien', hint: 'Người ngoài hành tinh' },
  { word: 'ankle', hint: 'Mắt cá chân' },
  { word: 'arrow', hint: 'Mũi tên' },
  { word: 'badge', hint: 'Huy hiệu' },
  { word: 'blank', hint: 'Trống' },
  { word: 'blink', hint: 'Chớp mắt' },
  { word: 'brick', hint: 'Viên gạch' },
  { word: 'broom', hint: 'Cái chổi' },
  { word: 'cabin', hint: 'Căn chòi' },
  { word: 'chalk', hint: 'Phấn viết' },
  { word: 'chase', hint: 'Đuổi theo' },
  { word: 'cheek', hint: 'Má' },
  { word: 'chess', hint: 'Cờ vua' },
  { word: 'chest', hint: 'Ngực / Rương' },
  { word: 'coast', hint: 'Bờ biển' },
  { word: 'coral', hint: 'San hô' },
  { word: 'couch', hint: 'Ghế dài' },
  { word: 'count', hint: 'Đếm' },
  { word: 'crash', hint: 'Va chạm' },
  { word: 'crown', hint: 'Vương miện' },
  { word: 'crush', hint: 'Nghiền nát' },
  { word: 'demon', hint: 'Quỷ' },
  { word: 'fairy', hint: 'Nàng tiên' },
  { word: 'fence', hint: 'Hàng rào' },
  { word: 'fiber', hint: 'Sợi' },
  { word: 'flame', hint: 'Ngọn lửa' },
  { word: 'float', hint: 'Nổi' },
  { word: 'flood', hint: 'Lũ lụt' },
  { word: 'flour', hint: 'Bột mì' },
  { word: 'frost', hint: 'Sương giá' },
  { word: 'fruit', hint: 'Trái cây' },
  { word: 'ghost', hint: 'Con ma' },
  { word: 'giant', hint: 'Người khổng lồ' },
  { word: 'globe', hint: 'Quả địa cầu' },
  { word: 'goose', hint: 'Con ngỗng' },
  { word: 'grain', hint: 'Hạt ngũ cốc' },
  { word: 'guard', hint: 'Bảo vệ' },
  { word: 'guess', hint: 'Đoán' },
  { word: 'guide', hint: 'Hướng dẫn viên' },
  { word: 'honey', hint: 'Mật ong' },
  { word: 'jewel', hint: 'Viên ngọc' },
  { word: 'juice', hint: 'Nước ép' },
  { word: 'kneel', hint: 'Quỳ' },
  { word: 'leash', hint: 'Dây xích' },
  { word: 'magic', hint: 'Phép thuật' },
  { word: 'medal', hint: 'Huy chương' },
  { word: 'metal', hint: 'Kim loại' },
  { word: 'motor', hint: 'Động cơ' },
  { word: 'olive', hint: 'Quả ô liu' },
  { word: 'otter', hint: 'Rái cá' },
  { word: 'paste', hint: 'Hồ dán' },
  { word: 'patch', hint: 'Miếng vá' },
  { word: 'pearl', hint: 'Ngọc trai' },
  { word: 'pedal', hint: 'Bàn đạp' },
  { word: 'penny', hint: 'Đồng xu' },
  { word: 'petal', hint: 'Cánh hoa' },
  { word: 'press', hint: 'Ấn / Ép' },
  { word: 'pride', hint: 'Niềm tự hào' },
  { word: 'prize', hint: 'Giải thưởng' },
  { word: 'proof', hint: 'Bằng chứng' },
  { word: 'pulse', hint: 'Mạch đập' },
  { word: 'pupil', hint: 'Học trò' },
  { word: 'quail', hint: 'Chim cút' },
  { word: 'radar', hint: 'Ra-đa' },
  { word: 'ranch', hint: 'Trang trại' },
  { word: 'ridge', hint: 'Sống núi' },
  { word: 'rival', hint: 'Đối thủ' },
  { word: 'robin', hint: 'Chim cổ đỏ' },
  { word: 'rural', hint: 'Nông thôn' },
  { word: 'sauce', hint: 'Nước sốt' },
  { word: 'scale', hint: 'Cân / Vảy' },
  { word: 'scent', hint: 'Mùi hương' },
  { word: 'scope', hint: 'Phạm vi' },
  { word: 'scout', hint: 'Hướng đạo sinh' },
  { word: 'shell', hint: 'Vỏ sò' },
  { word: 'shore', hint: 'Bờ biển' },
  { word: 'siege', hint: 'Bao vây' },
  { word: 'skull', hint: 'Hộp sọ' },
  { word: 'sloth', hint: 'Con lười' },
  { word: 'snail', hint: 'Con ốc sên' },
  { word: 'solar', hint: 'Mặt trời' },
  { word: 'space', hint: 'Không gian' },
  { word: 'spark', hint: 'Tia lửa' },
  { word: 'spear', hint: 'Ngọn giáo' },
  { word: 'spice', hint: 'Gia vị' },
  { word: 'spine', hint: 'Cột sống' },
  { word: 'spray', hint: 'Phun / Xịt' },
  { word: 'squad', hint: 'Đội' },
  { word: 'stack', hint: 'Chồng / Đống' },
  { word: 'stage', hint: 'Sân khấu' },
  { word: 'stain', hint: 'Vết bẩn' },
  { word: 'stair', hint: 'Bậc thang' },
  { word: 'stamp', hint: 'Con tem' },
  { word: 'stare', hint: 'Nhìn chằm chằm' },
  { word: 'steam', hint: 'Hơi nước' },
  { word: 'steel', hint: 'Thép' },
  { word: 'steep', hint: 'Dốc' },
  { word: 'stork', hint: 'Con cò' },
  { word: 'stove', hint: 'Bếp lò' },
  { word: 'straw', hint: 'Ống hút / Rơm' },
  { word: 'strip', hint: 'Dải / Thanh' },
  { word: 'stump', hint: 'Gốc cây' },
  { word: 'sugar', hint: 'Đường' },
  { word: 'swamp', hint: 'Đầm lầy' },
  { word: 'swarm', hint: 'Bầy (ong)' },
  { word: 'swing', hint: 'Xích đu' },
  { word: 'sword', hint: 'Thanh kiếm' },
  { word: 'syrup', hint: 'Xi rô' },
  { word: 'thorn', hint: 'Gai' },
  { word: 'toast', hint: 'Bánh mì nướng' },
  { word: 'torch', hint: 'Đuốc' },
  { word: 'trail', hint: 'Đường mòn' },
  { word: 'trout', hint: 'Cá hồi' },
  { word: 'trunk', hint: 'Thân cây' },
  { word: 'tulip', hint: 'Hoa tulip' },
  { word: 'vapor', hint: 'Hơi nước' },
  { word: 'vault', hint: 'Hầm' },
  { word: 'vigor', hint: 'Sức sống' },
  { word: 'viola', hint: 'Đàn viola' },
  { word: 'viper', hint: 'Rắn lục' },
  { word: 'vivid', hint: 'Sống động' },
  { word: 'wagon', hint: 'Xe ngựa' },
  { word: 'wheat', hint: 'Lúa mì' },
  { word: 'wheel', hint: 'Bánh xe' },
  { word: 'witch', hint: 'Phù thủy' },
  { word: 'youth', hint: 'Tuổi trẻ' },
  { word: 'zebra', hint: 'Ngựa vằn' },

  // ── 6 letters ──
  { word: 'flower', hint: 'Bông hoa' },
  { word: 'school', hint: 'Trường học' },
  { word: 'friend', hint: 'Bạn bè' },
  { word: 'family', hint: 'Gia đình' },
  { word: 'orange', hint: 'Quả cam' },
  { word: 'monkey', hint: 'Con khỉ' },
  { word: 'rabbit', hint: 'Con thỏ' },
  { word: 'mother', hint: 'Mẹ' },
  { word: 'father', hint: 'Bố' },
  { word: 'sister', hint: 'Chị/em gái' },
  { word: 'garden', hint: 'Khu vườn' },
  { word: 'winter', hint: 'Mùa đông' },
  { word: 'summer', hint: 'Mùa hè' },
  { word: 'banana', hint: 'Quả chuối' },
  { word: 'planet', hint: 'Hành tinh' },
  { word: 'parrot', hint: 'Con vẹt' },
  { word: 'turtle', hint: 'Con rùa' },
  { word: 'spider', hint: 'Con nhện' },
  { word: 'insect', hint: 'Côn trùng' },
  { word: 'kitten', hint: 'Mèo con' },
  { word: 'puppy', hint: 'Chó con' },
  { word: 'donkey', hint: 'Con lừa' },
  { word: 'pigeon', hint: 'Chim bồ câu' },
  { word: 'cherry', hint: 'Quả anh đào' },
  { word: 'potato', hint: 'Khoai tây' },
  { word: 'tomato', hint: 'Cà chua' },
  { word: 'carrot', hint: 'Cà rốt' },
  { word: 'pepper', hint: 'Ớt / Tiêu' },
  { word: 'cheese', hint: 'Phô mai' },
  { word: 'butter', hint: 'Bơ' },
  { word: 'coffee', hint: 'Cà phê' },
  { word: 'cookie', hint: 'Bánh quy' },
  { word: 'noodle', hint: 'Mì / Phở' },
  { word: 'dinner', hint: 'Bữa tối' },
  { word: 'bottle', hint: 'Chai / Lọ' },
  { word: 'basket', hint: 'Cái rổ' },
  { word: 'bucket', hint: 'Cái xô' },
  { word: 'mirror', hint: 'Gương' },
  { word: 'pillow', hint: 'Cái gối' },
  { word: 'window', hint: 'Cửa sổ' },
  { word: 'candle', hint: 'Cây nến' },
  { word: 'camera', hint: 'Máy ảnh' },
  { word: 'guitar', hint: 'Đàn ghi-ta' },
  { word: 'rocket', hint: 'Tên lửa' },
  { word: 'bridge', hint: 'Cây cầu' },
  { word: 'castle', hint: 'Lâu đài' },
  { word: 'temple', hint: 'Ngôi đền' },
  { word: 'market', hint: 'Chợ' },
  { word: 'street', hint: 'Đường phố' },
  { word: 'forest', hint: 'Rừng' },
  { word: 'island', hint: 'Hòn đảo' },
  { word: 'desert', hint: 'Sa mạc' },
  { word: 'spring', hint: 'Mùa xuân' },
  { word: 'autumn', hint: 'Mùa thu' },
  { word: 'people', hint: 'Mọi người' },
  { word: 'doctor', hint: 'Bác sĩ' },
  { word: 'police', hint: 'Cảnh sát' },
  { word: 'farmer', hint: 'Nông dân' },
  { word: 'singer', hint: 'Ca sĩ' },
  { word: 'driver', hint: 'Tài xế' },
  { word: 'jacket', hint: 'Áo khoác' },
  { word: 'sandal', hint: 'Dép' },
  { word: 'gloves', hint: 'Găng tay' },
  { word: 'tongue', hint: 'Cái lưỡi' },
  { word: 'finger', hint: 'Ngón tay' },
  { word: 'elbow', hint: 'Khuỷu tay' },
  { word: 'muscle', hint: 'Cơ bắp' },
  { word: 'silver', hint: 'Bạc' },
  { word: 'yellow', hint: 'Màu vàng' },
  { word: 'purple', hint: 'Màu tím' },
  { word: 'circle', hint: 'Hình tròn' },
  { word: 'square', hint: 'Hình vuông' },
  { word: 'number', hint: 'Con số' },
  { word: 'letter', hint: 'Chữ cái' },
  { word: 'pencil', hint: 'Bút chì' },
  { word: 'eraser', hint: 'Cục tẩy' },
  { word: 'listen', hint: 'Lắng nghe' },
  { word: 'travel', hint: 'Du lịch' },
  { word: 'flying', hint: 'Bay' },
  { word: 'frozen', hint: 'Đông lạnh' },
  { word: 'hungry', hint: 'Đói' },
  { word: 'thirst', hint: 'Khát' },
  { word: 'strong', hint: 'Mạnh mẽ' },
  { word: 'gentle', hint: 'Dịu dàng' },
  { word: 'scared', hint: 'Sợ hãi' },
  { word: 'cloudy', hint: 'Nhiều mây' },
  { word: 'snowy', hint: 'Có tuyết' },
  { word: 'stormy', hint: 'Bão' },
  { word: 'sunny', hint: 'Nắng' },
  { word: 'soccer', hint: 'Bóng đá' },
  { word: 'tennis', hint: 'Quần vợt' },
  { word: 'trophy', hint: 'Cúp / Giải' },
  { word: 'anchor', hint: 'Mỏ neo' },
  { word: 'badger', hint: 'Con lửng' },
  { word: 'bakery', hint: 'Tiệm bánh' },
  { word: 'ballet', hint: 'Múa ba lê' },
  { word: 'bamboo', hint: 'Tre' },
  { word: 'barber', hint: 'Thợ cắt tóc' },
  { word: 'barrel', hint: 'Thùng gỗ' },
  { word: 'beacon', hint: 'Ngọn hải đăng' },
  { word: 'beetle', hint: 'Con bọ cánh cứng' },
  { word: 'bishop', hint: 'Giám mục' },
  { word: 'blanket', hint: 'Chăn' },
  { word: 'bonnet', hint: 'Mũ trẻ em' },
  { word: 'bronze', hint: 'Đồng' },
  { word: 'bubble', hint: 'Bong bóng' },
  { word: 'cactus', hint: 'Cây xương rồng' },
  { word: 'canyon', hint: 'Hẻm núi' },
  { word: 'carpet', hint: 'Thảm' },
  { word: 'cellar', hint: 'Hầm rượu' },
  { word: 'cement', hint: 'Xi măng' },
  { word: 'circus', hint: 'Rạp xiếc' },
  { word: 'cobweb', hint: 'Mạng nhện' },
  { word: 'collar', hint: 'Cổ áo' },
  { word: 'column', hint: 'Cột' },
  { word: 'comet', hint: 'Sao chổi' },
  { word: 'copper', hint: 'Đồng đỏ' },
  { word: 'cotton', hint: 'Bông / Vải' },
  { word: 'cradle', hint: 'Nôi' },
  { word: 'crater', hint: 'Miệng núi lửa' },
  { word: 'cuckoo', hint: 'Chim cu cu' },
  { word: 'dagger', hint: 'Dao găm' },
  { word: 'dolphin', hint: 'Cá heo' },
  { word: 'dragon', hint: 'Con rồng' },
  { word: 'falcon', hint: 'Chim ưng' },
  { word: 'feather', hint: 'Lông vũ' },
  { word: 'ferret', hint: 'Chồn' },
  { word: 'fossil', hint: 'Hóa thạch' },
  { word: 'frozen', hint: 'Đông lạnh' },
  { word: 'funnel', hint: 'Phễu' },
  { word: 'galaxy', hint: 'Thiên hà' },
  { word: 'garlic', hint: 'Tỏi' },
  { word: 'geyser', hint: 'Mạch nước phun' },
  { word: 'ginger', hint: 'Gừng' },
  { word: 'goblet', hint: 'Ly có chân' },
  { word: 'gravel', hint: 'Sỏi' },
  { word: 'groove', hint: 'Rãnh' },
  { word: 'harbor', hint: 'Bến cảng' },
  { word: 'helmet', hint: 'Mũ bảo hiểm' },
  { word: 'heron', hint: 'Con diệc' },
  { word: 'hobbit', hint: 'Người lùn Hobbit' },
  { word: 'icicle', hint: 'Cột băng' },
  { word: 'iguana', hint: 'Kỳ nhông' },
  { word: 'kennel', hint: 'Chuồng chó' },
  { word: 'kettle', hint: 'Ấm đun nước' },
  { word: 'knight', hint: 'Hiệp sĩ' },
  { word: 'lagoon', hint: 'Đầm phá' },
  { word: 'lizard', hint: 'Con thằn lằn' },
  { word: 'locker', hint: 'Tủ khóa' },
  { word: 'magnet', hint: 'Nam châm' },
  { word: 'manger', hint: 'Máng cỏ' },
  { word: 'marble', hint: 'Viên bi' },
  { word: 'meadow', hint: 'Đồng cỏ' },
  { word: 'nectar', hint: 'Mật hoa' },
  { word: 'needle', hint: 'Cái kim' },
  { word: 'oyster', hint: 'Con hàu' },
  { word: 'paddle', hint: 'Mái chèo' },
  { word: 'pickle', hint: 'Dưa muối' },
  { word: 'pirate', hint: 'Cướp biển' },
  { word: 'pocket', hint: 'Túi áo' },
  { word: 'puzzle', hint: 'Câu đố' },
  { word: 'shovel', hint: 'Cái xẻng' },
  { word: 'statue', hint: 'Bức tượng' },
  { word: 'sunset', hint: 'Hoàng hôn' },
  { word: 'ticket', hint: 'Vé' },
  { word: 'tissue', hint: 'Khăn giấy' },

  // ── 7+ letters ──
  { word: 'kitchen', hint: 'Nhà bếp' },
  { word: 'teacher', hint: 'Giáo viên' },
  { word: 'picture', hint: 'Bức tranh' },
  { word: 'chicken', hint: 'Con gà' },
  { word: 'student', hint: 'Học sinh' },
  { word: 'rainbow', hint: 'Cầu vồng' },
  { word: 'morning', hint: 'Buổi sáng' },
  { word: 'evening', hint: 'Buổi tối' },
  { word: 'dolphin', hint: 'Cá heo' },
  { word: 'giraffe', hint: 'Hươu cao cổ' },
  { word: 'penguin', hint: 'Chim cánh cụt' },
  { word: 'octopus', hint: 'Bạch tuộc' },
  { word: 'lobster', hint: 'Tôm hùm' },
  { word: 'hamster', hint: 'Chuột hamster' },
  { word: 'panther', hint: 'Báo đen' },
  { word: 'buffalo', hint: 'Con trâu' },
  { word: 'sparrow', hint: 'Chim sẻ' },
  { word: 'peacock', hint: 'Con công' },
  { word: 'leopard', hint: 'Con báo' },
  { word: 'monster', hint: 'Quái vật' },
  { word: 'diamond', hint: 'Kim cương' },
  { word: 'volcano', hint: 'Núi lửa' },
  { word: 'weather', hint: 'Thời tiết' },
  { word: 'thunder', hint: 'Sấm sét' },
  { word: 'country', hint: 'Đất nước' },
  { word: 'village', hint: 'Ngôi làng' },
  { word: 'library', hint: 'Thư viện' },
  { word: 'airport', hint: 'Sân bay' },
  { word: 'stadium', hint: 'Sân vận động' },
  { word: 'hospital', hint: 'Bệnh viện' },
  { word: 'bedroom', hint: 'Phòng ngủ' },
  { word: 'bathroom', hint: 'Phòng tắm' },
  { word: 'umbrella', hint: 'Cái ô / Dù' },
  { word: 'backpack', hint: 'Ba lô' },
  { word: 'necklace', hint: 'Vòng cổ' },
  { word: 'bracelet', hint: 'Vòng tay' },
  { word: 'sandwich', hint: 'Bánh mì kẹp' },
  { word: 'pancake', hint: 'Bánh kếp' },
  { word: 'popcorn', hint: 'Bỏng ngô' },
  { word: 'pumpkin', hint: 'Bí ngô' },
  { word: 'cabbage', hint: 'Bắp cải' },
  { word: 'spinach', hint: 'Rau chân vịt' },
  { word: 'avocado', hint: 'Quả bơ' },
  { word: 'coconut', hint: 'Quả dừa' },
  { word: 'pineapple', hint: 'Quả dứa' },
  { word: 'blueberry', hint: 'Quả việt quất' },
  { word: 'strawberry', hint: 'Quả dâu tây' },
  { word: 'watermelon', hint: 'Quả dưa hấu' },
  { word: 'chocolate', hint: 'Sô cô la' },
  { word: 'spaghetti', hint: 'Mì Ý' },
  { word: 'hamburger', hint: 'Bánh hamburger' },
  { word: 'breakfast', hint: 'Bữa sáng' },
  { word: 'scissors', hint: 'Cái kéo' },
  { word: 'calendar', hint: 'Lịch' },
  { word: 'computer', hint: 'Máy tính' },
  { word: 'notebook', hint: 'Vở / Sổ tay' },
  { word: 'textbook', hint: 'Sách giáo khoa' },
  { word: 'magazine', hint: 'Tạp chí' },
  { word: 'birthday', hint: 'Sinh nhật' },
  { word: 'holiday', hint: 'Ngày lễ' },
  { word: 'weekend', hint: 'Cuối tuần' },
  { word: 'tonight', hint: 'Tối nay' },
  { word: 'sunlight', hint: 'Ánh nắng' },
  { word: 'moonlight', hint: 'Ánh trăng' },
  { word: 'mountain', hint: 'Ngọn núi' },
  { word: 'waterfall', hint: 'Thác nước' },
  { word: 'mushroom', hint: 'Nấm' },
  { word: 'treasure', hint: 'Kho báu' },
  { word: 'princess', hint: 'Công chúa' },
  { word: 'soldier', hint: 'Người lính' },
  { word: 'captain', hint: 'Thuyền trưởng' },
  { word: 'painter', hint: 'Họa sĩ' },
  { word: 'dentist', hint: 'Nha sĩ' },
  { word: 'fireman', hint: 'Lính cứu hỏa' },
  { word: 'brother', hint: 'Anh/em trai' },
  { word: 'grandma', hint: 'Bà' },
  { word: 'grandpa', hint: 'Ông' },
  { word: 'husband', hint: 'Chồng' },
  { word: 'neighbor', hint: 'Hàng xóm' },
  { word: 'shoulder', hint: 'Vai' },
  { word: 'stomach', hint: 'Bụng / Dạ dày' },
  { word: 'elephant', hint: 'Con voi' },
  { word: 'squirrel', hint: 'Con sóc' },
  { word: 'kangaroo', hint: 'Chuột túi' },
  { word: 'flamingo', hint: 'Hồng hạc' },
  { word: 'goldfish', hint: 'Cá vàng' },
  { word: 'starfish', hint: 'Sao biển' },
  { word: 'butterfly', hint: 'Con bướm' },
  { word: 'jellyfish', hint: 'Con sứa' },
  { word: 'crocodile', hint: 'Cá sấu' },
  { word: 'dragonfly', hint: 'Chuồn chuồn' },
  { word: 'sunflower', hint: 'Hoa hướng dương' },
  { word: 'classroom', hint: 'Lớp học' },
  { word: 'building', hint: 'Tòa nhà' },
  { word: 'playground', hint: 'Sân chơi' },
  { word: 'universe', hint: 'Vũ trụ' },
  { word: 'triangle', hint: 'Hình tam giác' },
  { word: 'rectangle', hint: 'Hình chữ nhật' },
  { word: 'question', hint: 'Câu hỏi' },
  { word: 'language', hint: 'Ngôn ngữ' },
  { word: 'alphabet', hint: 'Bảng chữ cái' },
  { word: 'painting', hint: 'Bức tranh' },
  { word: 'exercise', hint: 'Bài tập' },
  { word: 'swimming', hint: 'Bơi lội' },
  { word: 'running', hint: 'Chạy bộ' },
  { word: 'sleeping', hint: 'Đang ngủ' },
  { word: 'shopping', hint: 'Mua sắm' },
  { word: 'champion', hint: 'Nhà vô địch' },
  { word: 'dinosaur', hint: 'Khủng long' },
  { word: 'address', hint: 'Địa chỉ' },
  { word: 'balcony', hint: 'Ban công' },
  { word: 'battery', hint: 'Pin' },
  { word: 'blanket', hint: 'Chăn mền' },
  { word: 'cabinet', hint: 'Tủ' },
  { word: 'ceiling', hint: 'Trần nhà' },
  { word: 'century', hint: 'Thế kỷ' },
  { word: 'chamber', hint: 'Phòng' },
  { word: 'channel', hint: 'Kênh' },
  { word: 'chapter', hint: 'Chương' },
  { word: 'coconut', hint: 'Quả dừa' },
  { word: 'concert', hint: 'Buổi hòa nhạc' },
  { word: 'dessert', hint: 'Món tráng miệng' },
  { word: 'display', hint: 'Màn hình' },
  { word: 'factory', hint: 'Nhà máy' },
  { word: 'pajamas', hint: 'Đồ ngủ' },
  { word: 'panther', hint: 'Báo đen' },
  { word: 'parking', hint: 'Bãi đỗ xe' },
  { word: 'popcorn', hint: 'Bỏng ngô' },
  { word: 'pyramid', hint: 'Kim tự tháp' },
  { word: 'reindeer', hint: 'Tuần lộc' },
  { word: 'rooster', hint: 'Gà trống' },
  { word: 'seagull', hint: 'Chim hải âu' },
  { word: 'shrimp', hint: 'Con tôm' },
  { word: 'silence', hint: 'Sự im lặng' },
  { word: 'skating', hint: 'Trượt băng' },
  { word: 'snowman', hint: 'Người tuyết' },
  { word: 'tornado', hint: 'Lốc xoáy' },
  { word: 'tourist', hint: 'Du khách' },
  { word: 'unicorn', hint: 'Kỳ lân' },
  { word: 'uniform', hint: 'Đồng phục' },
  { word: 'vampire', hint: 'Ma cà rồng' },
  { word: 'vanilla', hint: 'Vani' },
  { word: 'vinegar', hint: 'Giấm' },
  { word: 'volcano', hint: 'Núi lửa' },
  { word: 'aquarium', hint: 'Bể cá' },
  { word: 'cucumber', hint: 'Dưa chuột' },
  { word: 'firework', hint: 'Pháo hoa' },
  { word: 'furniture', hint: 'Đồ nội thất' },
  { word: 'gentleman', hint: 'Quý ông' },
  { word: 'geography', hint: 'Địa lý' },
  { word: 'goldfish', hint: 'Cá vàng' },
  
]

export default WORD_BANK
