// Shared word bank for pet training games
// English words with Vietnamese hints, organized by category
const WORD_BANK = [
  // ── Animals ──
  { word: 'ant', hint: 'Con kien', category: 'animals' },
  { word: 'badger', hint: 'Con lung', category: 'animals' },
  { word: 'bat', hint: 'Con doi', category: 'animals' },
  { word: 'bear', hint: 'Con gau', category: 'animals' },
  { word: 'bee', hint: 'Con ong', category: 'animals' },
  { word: 'bird', hint: 'Con chim', category: 'animals' },
  { word: 'buffalo', hint: 'Con trau', category: 'animals' },
  { word: 'butterfly', hint: 'Con buom', category: 'animals' },
  { word: 'camel', hint: 'Con lac da', category: 'animals' },
  { word: 'cat', hint: 'Con meo', category: 'animals' },
  { word: 'chicken', hint: 'Con ga', category: 'animals' },
  { word: 'cow', hint: 'Con bo', category: 'animals' },
  { word: 'crab', hint: 'Con cua', category: 'animals' },
  { word: 'crocodile', hint: 'Ca sau', category: 'animals' },
  { word: 'crow', hint: 'Con qua', category: 'animals' },
  { word: 'cub', hint: 'Thu con', category: 'animals' },
  { word: 'cuckoo', hint: 'Chim cu cu', category: 'animals' },
  { word: 'deer', hint: 'Con huou', category: 'animals' },
  { word: 'dinosaur', hint: 'Khung long', category: 'animals' },
  { word: 'dog', hint: 'Con cho', category: 'animals' },
  { word: 'dolphin', hint: 'Ca heo', category: 'animals' },
  { word: 'donkey', hint: 'Con lua', category: 'animals' },
  { word: 'dove', hint: 'Chim bo cau', category: 'animals' },
  { word: 'dragon', hint: 'Con rong', category: 'animals' },
  { word: 'dragonfly', hint: 'Chuon chuon', category: 'animals' },
  { word: 'duck', hint: 'Con vit', category: 'animals' },
  { word: 'eagle', hint: 'Dai bang', category: 'animals' },
  { word: 'elephant', hint: 'Con voi', category: 'animals' },
  { word: 'falcon', hint: 'Chim ung', category: 'animals' },
  { word: 'fin', hint: 'Vay ca', category: 'animals' },
  { word: 'fish', hint: 'Con ca', category: 'animals' },
  { word: 'flamingo', hint: 'Hong hac', category: 'animals' },
  { word: 'fly', hint: 'Con ruoi', category: 'animals' },
  { word: 'fox', hint: 'Con cao', category: 'animals' },
  { word: 'frog', hint: 'Con ech', category: 'animals' },
  { word: 'giraffe', hint: 'Huou cao co', category: 'animals' },
  { word: 'goat', hint: 'Con de', category: 'animals' },
  { word: 'goldfish', hint: 'Ca vang', category: 'animals' },
  { word: 'goose', hint: 'Con ngong', category: 'animals' },
  { word: 'hamster', hint: 'Chuot hamster', category: 'animals' },
  { word: 'hare', hint: 'Tho rung', category: 'animals' },
  { word: 'hawk', hint: 'Chim ung', category: 'animals' },
  { word: 'hen', hint: 'Ga mai', category: 'animals' },
  { word: 'insect', hint: 'Con trung', category: 'animals' },
  { word: 'jellyfish', hint: 'Con sua', category: 'animals' },
  { word: 'kangaroo', hint: 'Chuot tui', category: 'animals' },
  { word: 'kitten', hint: 'Meo con', category: 'animals' },
  { word: 'leopard', hint: 'Con bao', category: 'animals' },
  { word: 'lion', hint: 'Con su tu', category: 'animals' },
  { word: 'lizard', hint: 'Con than lan', category: 'animals' },
  { word: 'lobster', hint: 'Tom hum', category: 'animals' },
  { word: 'monkey', hint: 'Con khi', category: 'animals' },
  { word: 'mouse', hint: 'Con chuot', category: 'animals' },
  { word: 'octopus', hint: 'Bach tuoc', category: 'animals' },
  { word: 'otter', hint: 'Rai ca', category: 'animals' },
  { word: 'owl', hint: 'Con cu', category: 'animals' },
  { word: 'oyster', hint: 'Con hau', category: 'animals' },
  { word: 'panda', hint: 'Gau truc', category: 'animals' },
  { word: 'panther', hint: 'Bao den', category: 'animals' },
  { word: 'parrot', hint: 'Con vet', category: 'animals' },
  { word: 'peacock', hint: 'Con cong', category: 'animals' },
  { word: 'penguin', hint: 'Chim canh cut', category: 'animals' },
  { word: 'pig', hint: 'Con lon', category: 'animals' },
  { word: 'pigeon', hint: 'Chim bo cau', category: 'animals' },
  { word: 'puppy', hint: 'Cho con', category: 'animals' },
  { word: 'rabbit', hint: 'Con tho', category: 'animals' },
  { word: 'ram', hint: 'Cuu duc', category: 'animals' },
  { word: 'reindeer', hint: 'Tuan loc', category: 'animals' },
  { word: 'rooster', hint: 'Ga trong', category: 'animals' },
  { word: 'seagull', hint: 'Chim hai au', category: 'animals' },
  { word: 'seal', hint: 'Hai cau', category: 'animals' },
  { word: 'shark', hint: 'Ca map', category: 'animals' },
  { word: 'sheep', hint: 'Con cuu', category: 'animals' },
  { word: 'shrimp', hint: 'Con tom', category: 'animals' },
  { word: 'sloth', hint: 'Con luoi', category: 'animals' },
  { word: 'snail', hint: 'Con oc sen', category: 'animals' },
  { word: 'snake', hint: 'Con ran', category: 'animals' },
  { word: 'sparrow', hint: 'Chim se', category: 'animals' },
  { word: 'spider', hint: 'Con nhen', category: 'animals' },
  { word: 'squirrel', hint: 'Con soc', category: 'animals' },
  { word: 'starfish', hint: 'Sao bien', category: 'animals' },
  { word: 'stork', hint: 'Con co', category: 'animals' },
  { word: 'swan', hint: 'Thien nga', category: 'animals' },
  { word: 'tiger', hint: 'Con ho', category: 'animals' },
  { word: 'tuna', hint: 'Ca ngu', category: 'animals' },
  { word: 'turtle', hint: 'Con rua', category: 'animals' },
  { word: 'unicorn', hint: 'Ky lan', category: 'animals' },
  { word: 'viper', hint: 'Ran luc', category: 'animals' },
  { word: 'whale', hint: 'Ca voi', category: 'animals' },
  { word: 'wolf', hint: 'Con soi', category: 'animals' },
  { word: 'worm', hint: 'Con sau', category: 'animals' },
  { word: 'zebra', hint: 'Ngua van', category: 'animals' },

  // ── Fruits ──
  { word: 'apple', hint: 'Qua tao', category: 'fruits' },
  { word: 'avocado', hint: 'Qua bo', category: 'fruits' },
  { word: 'banana', hint: 'Qua chuoi', category: 'fruits' },
  { word: 'blueberry', hint: 'Qua viet quat', category: 'fruits' },
  { word: 'cherry', hint: 'Qua anh dao', category: 'fruits' },
  { word: 'coconut', hint: 'Qua dua', category: 'fruits' },
  { word: 'fig', hint: 'Qua sung', category: 'fruits' },
  { word: 'fruit', hint: 'Trai cay', category: 'fruits' },
  { word: 'grape', hint: 'Qua nho', category: 'fruits' },
  { word: 'lemon', hint: 'Qua chanh vang', category: 'fruits' },
  { word: 'lime', hint: 'Qua chanh', category: 'fruits' },
  { word: 'mango', hint: 'Qua xoai', category: 'fruits' },
  { word: 'melon', hint: 'Qua dua', category: 'fruits' },
  { word: 'olive', hint: 'Qua o liu', category: 'fruits' },
  { word: 'orange', hint: 'Qua cam', category: 'fruits' },
  { word: 'peach', hint: 'Qua dao', category: 'fruits' },
  { word: 'pear', hint: 'Qua le', category: 'fruits' },
  { word: 'pineapple', hint: 'Qua dua', category: 'fruits' },
  { word: 'strawberry', hint: 'Qua dau tay', category: 'fruits' },
  { word: 'watermelon', hint: 'Qua dua hau', category: 'fruits' },
  { word: 'yam', hint: 'Khoai mo', category: 'fruits' },

  // ── Food & Drinks ──
  { word: 'bean', hint: 'Hat dau', category: 'food' },
  { word: 'bread', hint: 'Banh mi', category: 'food' },
  { word: 'breakfast', hint: 'Bua sang', category: 'food' },
  { word: 'butter', hint: 'Bo', category: 'food' },
  { word: 'cabbage', hint: 'Bap cai', category: 'food' },
  { word: 'cake', hint: 'Banh', category: 'food' },
  { word: 'candy', hint: 'Keo', category: 'food' },
  { word: 'carrot', hint: 'Ca rot', category: 'food' },
  { word: 'cheese', hint: 'Pho mai', category: 'food' },
  { word: 'chocolate', hint: 'So co la', category: 'food' },
  { word: 'coffee', hint: 'Ca phe', category: 'food' },
  { word: 'cookie', hint: 'Banh quy', category: 'food' },
  { word: 'corn', hint: 'Ngo / Bap', category: 'food' },
  { word: 'cucumber', hint: 'Dua chuot', category: 'food' },
  { word: 'dessert', hint: 'Mon trang mieng', category: 'food' },
  { word: 'dinner', hint: 'Bua toi', category: 'food' },
  { word: 'egg', hint: 'Qua trung', category: 'food' },
  { word: 'flour', hint: 'Bot mi', category: 'food' },
  { word: 'garlic', hint: 'Toi', category: 'food' },
  { word: 'ginger', hint: 'Gung', category: 'food' },
  { word: 'hamburger', hint: 'Banh hamburger', category: 'food' },
  { word: 'honey', hint: 'Mat ong', category: 'food' },
  { word: 'ice', hint: 'Da / Bang', category: 'food' },
  { word: 'jam', hint: 'Mut', category: 'food' },
  { word: 'juice', hint: 'Nuoc ep', category: 'food' },
  { word: 'lunch', hint: 'Bua trua', category: 'food' },
  { word: 'meat', hint: 'Thit', category: 'food' },
  { word: 'milk', hint: 'Sua', category: 'food' },
  { word: 'mushroom', hint: 'Nam', category: 'food' },
  { word: 'noodle', hint: 'Mi / Pho', category: 'food' },
  { word: 'nut', hint: 'Hat', category: 'food' },
  { word: 'onion', hint: 'Cu hanh', category: 'food' },
  { word: 'pancake', hint: 'Banh kep', category: 'food' },
  { word: 'pepper', hint: 'Ot / Tieu', category: 'food' },
  { word: 'pickle', hint: 'Dua muoi', category: 'food' },
  { word: 'pie', hint: 'Banh nuong', category: 'food' },
  { word: 'pizza', hint: 'Banh pizza', category: 'food' },
  { word: 'popcorn', hint: 'Bong ngo', category: 'food' },
  { word: 'potato', hint: 'Khoai tay', category: 'food' },
  { word: 'pumpkin', hint: 'Bi ngo', category: 'food' },
  { word: 'rice', hint: 'Gao / Com', category: 'food' },
  { word: 'salad', hint: 'Rau tron', category: 'food' },
  { word: 'salt', hint: 'Muoi', category: 'food' },
  { word: 'sandwich', hint: 'Banh mi kep', category: 'food' },
  { word: 'sauce', hint: 'Nuoc sot', category: 'food' },
  { word: 'soup', hint: 'Sup / Canh', category: 'food' },
  { word: 'spaghetti', hint: 'Mi Y', category: 'food' },
  { word: 'spice', hint: 'Gia vi', category: 'food' },
  { word: 'sugar', hint: 'Duong', category: 'food' },
  { word: 'syrup', hint: 'Xi ro', category: 'food' },
  { word: 'toast', hint: 'Banh mi nuong', category: 'food' },
  { word: 'tomato', hint: 'Ca chua', category: 'food' },
  { word: 'vanilla', hint: 'Vani', category: 'food' },
  { word: 'vinegar', hint: 'Giam', category: 'food' },
  { word: 'wheat', hint: 'Lua mi', category: 'food' },

  // ── Body Parts ──
  { word: 'ankle', hint: 'Mat ca chan', category: 'body' },
  { word: 'arm', hint: 'Canh tay', category: 'body' },
  { word: 'blood', hint: 'Mau', category: 'body' },
  { word: 'bone', hint: 'Xuong', category: 'body' },
  { word: 'brain', hint: 'Bo nao', category: 'body' },
  { word: 'cheek', hint: 'Ma', category: 'body' },
  { word: 'chest', hint: 'Nguc / Ruong', category: 'body' },
  { word: 'chin', hint: 'Cam', category: 'body' },
  { word: 'ear', hint: 'Cai tai', category: 'body' },
  { word: 'elbow', hint: 'Khuyu tay', category: 'body' },
  { word: 'eye', hint: 'Con mat', category: 'body' },
  { word: 'face', hint: 'Khuon mat', category: 'body' },
  { word: 'finger', hint: 'Ngon tay', category: 'body' },
  { word: 'foot', hint: 'Ban chan', category: 'body' },
  { word: 'fur', hint: 'Long thu', category: 'body' },
  { word: 'hair', hint: 'Toc', category: 'body' },
  { word: 'hand', hint: 'Ban tay', category: 'body' },
  { word: 'heart', hint: 'Trai tim', category: 'body' },
  { word: 'heel', hint: 'Got chan', category: 'body' },
  { word: 'jaw', hint: 'Ham', category: 'body' },
  { word: 'leg', hint: 'Cai chan', category: 'body' },
  { word: 'lip', hint: 'Moi', category: 'body' },
  { word: 'mouth', hint: 'Mieng', category: 'body' },
  { word: 'muscle', hint: 'Co bap', category: 'body' },
  { word: 'neck', hint: 'Co', category: 'body' },
  { word: 'nose', hint: 'Cai mui', category: 'body' },
  { word: 'rib', hint: 'Xuong suon', category: 'body' },
  { word: 'shoulder', hint: 'Vai', category: 'body' },
  { word: 'skull', hint: 'Hop so', category: 'body' },
  { word: 'spine', hint: 'Cot song', category: 'body' },
  { word: 'stomach', hint: 'Bung / Da day', category: 'body' },
  { word: 'tail', hint: 'Cai duoi', category: 'body' },
  { word: 'teeth', hint: 'Rang', category: 'body' },
  { word: 'tongue', hint: 'Cai luoi', category: 'body' },
  { word: 'wing', hint: 'Canh (chim)', category: 'body' },

  // ── Nature & Weather ──
  { word: 'autumn', hint: 'Mua thu', category: 'nature' },
  { word: 'bamboo', hint: 'Tre', category: 'nature' },
  { word: 'bay', hint: 'Vinh', category: 'nature' },
  { word: 'beach', hint: 'Bai bien', category: 'nature' },
  { word: 'cactus', hint: 'Cay xuong rong', category: 'nature' },
  { word: 'canyon', hint: 'Hem nui', category: 'nature' },
  { word: 'clay', hint: 'Dat set', category: 'nature' },
  { word: 'cloud', hint: 'Dam may', category: 'nature' },
  { word: 'coal', hint: 'Than', category: 'nature' },
  { word: 'coast', hint: 'Bo bien', category: 'nature' },
  { word: 'coral', hint: 'San ho', category: 'nature' },
  { word: 'desert', hint: 'Sa mac', category: 'nature' },
  { word: 'dew', hint: 'Suong', category: 'nature' },
  { word: 'dusk', hint: 'Hoang hon', category: 'nature' },
  { word: 'dust', hint: 'Bui', category: 'nature' },
  { word: 'earth', hint: 'Trai dat', category: 'nature' },
  { word: 'field', hint: 'Canh dong', category: 'nature' },
  { word: 'fire', hint: 'Lua', category: 'nature' },
  { word: 'flame', hint: 'Ngon lua', category: 'nature' },
  { word: 'flood', hint: 'Lu lut', category: 'nature' },
  { word: 'flower', hint: 'Bong hoa', category: 'nature' },
  { word: 'fog', hint: 'Suong mu', category: 'nature' },
  { word: 'forest', hint: 'Rung', category: 'nature' },
  { word: 'fossil', hint: 'Hoa thach', category: 'nature' },
  { word: 'galaxy', hint: 'Thien ha', category: 'nature' },
  { word: 'garden', hint: 'Khu vuon', category: 'nature' },
  { word: 'grass', hint: 'Co', category: 'nature' },
  { word: 'hive', hint: 'To ong', category: 'nature' },
  { word: 'island', hint: 'Hon dao', category: 'nature' },
  { word: 'lake', hint: 'Ho nuoc', category: 'nature' },
  { word: 'leaf', hint: 'Chiec la', category: 'nature' },
  { word: 'light', hint: 'Anh sang', category: 'nature' },
  { word: 'log', hint: 'Khuc go', category: 'nature' },
  { word: 'moon', hint: 'Mat trang', category: 'nature' },
  { word: 'moonlight', hint: 'Anh trang', category: 'nature' },
  { word: 'mountain', hint: 'Ngon nui', category: 'nature' },
  { word: 'mud', hint: 'Bun', category: 'nature' },
  { word: 'nest', hint: 'To chim', category: 'nature' },
  { word: 'oak', hint: 'Cay soi', category: 'nature' },
  { word: 'ocean', hint: 'Dai duong', category: 'nature' },
  { word: 'planet', hint: 'Hanh tinh', category: 'nature' },
  { word: 'pond', hint: 'Ao', category: 'nature' },
  { word: 'rain', hint: 'Mua', category: 'nature' },
  { word: 'rainbow', hint: 'Cau vong', category: 'nature' },
  { word: 'reef', hint: 'Ran san ho', category: 'nature' },
  { word: 'river', hint: 'Dong song', category: 'nature' },
  { word: 'rose', hint: 'Hoa hong', category: 'nature' },
  { word: 'sand', hint: 'Cat', category: 'nature' },
  { word: 'sea', hint: 'Bien', category: 'nature' },
  { word: 'seed', hint: 'Hat giong', category: 'nature' },
  { word: 'shell', hint: 'Vo so', category: 'nature' },
  { word: 'shore', hint: 'Bo bien', category: 'nature' },
  { word: 'sky', hint: 'Bau troi', category: 'nature' },
  { word: 'snow', hint: 'Tuyet', category: 'nature' },
  { word: 'solar', hint: 'Mat troi', category: 'nature' },
  { word: 'space', hint: 'Khong gian', category: 'nature' },
  { word: 'spark', hint: 'Tia lua', category: 'nature' },
  { word: 'spring', hint: 'Mua xuan', category: 'nature' },
  { word: 'star', hint: 'Ngoi sao', category: 'nature' },
  { word: 'steam', hint: 'Hoi nuoc', category: 'nature' },
  { word: 'stone', hint: 'Hon da', category: 'nature' },
  { word: 'summer', hint: 'Mua he', category: 'nature' },
  { word: 'sun', hint: 'Mat troi', category: 'nature' },
  { word: 'sunflower', hint: 'Hoa huong duong', category: 'nature' },
  { word: 'sunlight', hint: 'Anh nang', category: 'nature' },
  { word: 'sunset', hint: 'Hoang hon', category: 'nature' },
  { word: 'swamp', hint: 'Dam lay', category: 'nature' },
  { word: 'thorn', hint: 'Gai', category: 'nature' },
  { word: 'thunder', hint: 'Sam set', category: 'nature' },
  { word: 'tornado', hint: 'Loc xoay', category: 'nature' },
  { word: 'tree', hint: 'Cai cay', category: 'nature' },
  { word: 'trunk', hint: 'Than cay', category: 'nature' },
  { word: 'tulip', hint: 'Hoa tulip', category: 'nature' },
  { word: 'universe', hint: 'Vu tru', category: 'nature' },
  { word: 'vine', hint: 'Day leo', category: 'nature' },
  { word: 'volcano', hint: 'Nui lua', category: 'nature' },
  { word: 'waterfall', hint: 'Thac nuoc', category: 'nature' },
  { word: 'weather', hint: 'Thoi tiet', category: 'nature' },
  { word: 'wind', hint: 'Gio', category: 'nature' },
  { word: 'winter', hint: 'Mua dong', category: 'nature' },

  // ── Colors ──
  { word: 'black', hint: 'Mau den', category: 'colors' },
  { word: 'blue', hint: 'Mau xanh duong', category: 'colors' },
  { word: 'bronze', hint: 'Dong', category: 'colors' },
  { word: 'brown', hint: 'Mau nau', category: 'colors' },
  { word: 'color', hint: 'Mau sac', category: 'colors' },
  { word: 'gold', hint: 'Vang', category: 'colors' },
  { word: 'gray', hint: 'Mau xam', category: 'colors' },
  { word: 'green', hint: 'Mau xanh la', category: 'colors' },
  { word: 'pink', hint: 'Mau hong', category: 'colors' },
  { word: 'purple', hint: 'Mau tim', category: 'colors' },
  { word: 'red', hint: 'Mau do', category: 'colors' },
  { word: 'silver', hint: 'Bac', category: 'colors' },
  { word: 'white', hint: 'Mau trang', category: 'colors' },
  { word: 'yellow', hint: 'Mau vang', category: 'colors' },

  // ── Clothing ──
  { word: 'backpack', hint: 'Ba lo', category: 'clothing' },
  { word: 'bracelet', hint: 'Vong tay', category: 'clothing' },
  { word: 'coat', hint: 'Ao khoac', category: 'clothing' },
  { word: 'collar', hint: 'Co ao', category: 'clothing' },
  { word: 'dress', hint: 'Vay dai', category: 'clothing' },
  { word: 'gloves', hint: 'Gang tay', category: 'clothing' },
  { word: 'hat', hint: 'Cai mu', category: 'clothing' },
  { word: 'helmet', hint: 'Mu bao hiem', category: 'clothing' },
  { word: 'jacket', hint: 'Ao khoac', category: 'clothing' },
  { word: 'necklace', hint: 'Vong co', category: 'clothing' },
  { word: 'pajamas', hint: 'Do ngu', category: 'clothing' },
  { word: 'pants', hint: 'Quan dai', category: 'clothing' },
  { word: 'pocket', hint: 'Tui ao', category: 'clothing' },
  { word: 'ring', hint: 'Chiec nhan', category: 'clothing' },
  { word: 'sandal', hint: 'Dep', category: 'clothing' },
  { word: 'scarf', hint: 'Khan quang', category: 'clothing' },
  { word: 'shirt', hint: 'Ao so mi', category: 'clothing' },
  { word: 'shoe', hint: 'Giay', category: 'clothing' },
  { word: 'skirt', hint: 'Vay ngan', category: 'clothing' },
  { word: 'sock', hint: 'Tat / Vo', category: 'clothing' },
  { word: 'umbrella', hint: 'Cai o / Du', category: 'clothing' },
  { word: 'uniform', hint: 'Dong phuc', category: 'clothing' },
  { word: 'vest', hint: 'Ao ghi le', category: 'clothing' },

  // ── Objects & Tools ──
  { word: 'anchor', hint: 'Mo neo', category: 'objects' },
  { word: 'arrow', hint: 'Mui ten', category: 'objects' },
  { word: 'axe', hint: 'Cai riu', category: 'objects' },
  { word: 'badge', hint: 'Huy hieu', category: 'objects' },
  { word: 'bag', hint: 'Cai tui', category: 'objects' },
  { word: 'ball', hint: 'Qua bong', category: 'objects' },
  { word: 'basket', hint: 'Cai ro', category: 'objects' },
  { word: 'battery', hint: 'Pin', category: 'objects' },
  { word: 'bed', hint: 'Cai giuong', category: 'objects' },
  { word: 'bell', hint: 'Cai chuong', category: 'objects' },
  { word: 'blanket', hint: 'Chan men', category: 'objects' },
  { word: 'book', hint: 'Quyen sach', category: 'objects' },
  { word: 'bottle', hint: 'Chai / Lo', category: 'objects' },
  { word: 'bow', hint: 'Cai cung', category: 'objects' },
  { word: 'box', hint: 'Cai hop', category: 'objects' },
  { word: 'brick', hint: 'Vien gach', category: 'objects' },
  { word: 'broom', hint: 'Cai choi', category: 'objects' },
  { word: 'brush', hint: 'Ban chai', category: 'objects' },
  { word: 'bubble', hint: 'Bong bong', category: 'objects' },
  { word: 'bucket', hint: 'Cai xo', category: 'objects' },
  { word: 'cabinet', hint: 'Tu', category: 'objects' },
  { word: 'calendar', hint: 'Lich', category: 'objects' },
  { word: 'camera', hint: 'May anh', category: 'objects' },
  { word: 'candle', hint: 'Cay nen', category: 'objects' },
  { word: 'carpet', hint: 'Tham', category: 'objects' },
  { word: 'cement', hint: 'Xi mang', category: 'objects' },
  { word: 'chair', hint: 'Cai ghe', category: 'objects' },
  { word: 'chalk', hint: 'Phan viet', category: 'objects' },
  { word: 'clock', hint: 'Dong ho', category: 'objects' },
  { word: 'coin', hint: 'Dong xu', category: 'objects' },
  { word: 'column', hint: 'Cot', category: 'objects' },
  { word: 'computer', hint: 'May tinh', category: 'objects' },
  { word: 'cotton', hint: 'Bong / Vai', category: 'objects' },
  { word: 'crown', hint: 'Vuong mien', category: 'objects' },
  { word: 'cube', hint: 'Hinh lap phuong', category: 'objects' },
  { word: 'cup', hint: 'Cai coc', category: 'objects' },
  { word: 'diamond', hint: 'Kim cuong', category: 'objects' },
  { word: 'door', hint: 'Cai cua', category: 'objects' },
  { word: 'drum', hint: 'Cai trong', category: 'objects' },
  { word: 'eraser', hint: 'Cuc tay', category: 'objects' },
  { word: 'fan', hint: 'Cai quat', category: 'objects' },
  { word: 'feather', hint: 'Long vu', category: 'objects' },
  { word: 'firework', hint: 'Phao hoa', category: 'objects' },
  { word: 'flag', hint: 'La co', category: 'objects' },
  { word: 'fork', hint: 'Cai nia', category: 'objects' },
  { word: 'fuel', hint: 'Nhien lieu', category: 'objects' },
  { word: 'furniture', hint: 'Do noi that', category: 'objects' },
  { word: 'gate', hint: 'Cong', category: 'objects' },
  { word: 'gear', hint: 'Banh rang', category: 'objects' },
  { word: 'gem', hint: 'Vien ngoc', category: 'objects' },
  { word: 'glass', hint: 'Cai ly', category: 'objects' },
  { word: 'glue', hint: 'Keo dan', category: 'objects' },
  { word: 'guitar', hint: 'Dan ghi-ta', category: 'objects' },
  { word: 'horn', hint: 'Sung', category: 'objects' },
  { word: 'ink', hint: 'Muc', category: 'objects' },
  { word: 'iron', hint: 'Sat', category: 'objects' },
  { word: 'jar', hint: 'Cai lo', category: 'objects' },
  { word: 'jewel', hint: 'Vien ngoc', category: 'objects' },
  { word: 'kettle', hint: 'Am dun nuoc', category: 'objects' },
  { word: 'key', hint: 'Chia khoa', category: 'objects' },
  { word: 'kite', hint: 'Con dieu', category: 'objects' },
  { word: 'knife', hint: 'Con dao', category: 'objects' },
  { word: 'knot', hint: 'Nut that', category: 'objects' },
  { word: 'lamp', hint: 'Cai den', category: 'objects' },
  { word: 'leash', hint: 'Day xich', category: 'objects' },
  { word: 'locker', hint: 'Tu khoa', category: 'objects' },
  { word: 'magazine', hint: 'Tap chi', category: 'objects' },
  { word: 'magnet', hint: 'Nam cham', category: 'objects' },
  { word: 'map', hint: 'Ban do', category: 'objects' },
  { word: 'marble', hint: 'Vien bi', category: 'objects' },
  { word: 'medal', hint: 'Huy chuong', category: 'objects' },
  { word: 'metal', hint: 'Kim loai', category: 'objects' },
  { word: 'mirror', hint: 'Guong', category: 'objects' },
  { word: 'nail', hint: 'Cai dinh', category: 'objects' },
  { word: 'needle', hint: 'Cai kim', category: 'objects' },
  { word: 'net', hint: 'Cai luoi', category: 'objects' },
  { word: 'notebook', hint: 'Vo / So tay', category: 'objects' },
  { word: 'oven', hint: 'Lo nuong', category: 'objects' },
  { word: 'pearl', hint: 'Ngoc trai', category: 'objects' },
  { word: 'pedal', hint: 'Ban dap', category: 'objects' },
  { word: 'pen', hint: 'Cai but', category: 'objects' },
  { word: 'pencil', hint: 'But chi', category: 'objects' },
  { word: 'penny', hint: 'Dong xu', category: 'objects' },
  { word: 'phone', hint: 'Dien thoai', category: 'objects' },
  { word: 'piano', hint: 'Dan piano', category: 'objects' },
  { word: 'pillow', hint: 'Cai goi', category: 'objects' },
  { word: 'plate', hint: 'Cai dia', category: 'objects' },
  { word: 'pot', hint: 'Cai noi', category: 'objects' },
  { word: 'prize', hint: 'Giai thuong', category: 'objects' },
  { word: 'puzzle', hint: 'Cau do', category: 'objects' },
  { word: 'radio', hint: 'Dai radio', category: 'objects' },
  { word: 'rocket', hint: 'Ten lua', category: 'objects' },
  { word: 'rope', hint: 'Day thung', category: 'objects' },
  { word: 'ruby', hint: 'Hong ngoc', category: 'objects' },
  { word: 'rug', hint: 'Tam tham', category: 'objects' },
  { word: 'sail', hint: 'Canh buom', category: 'objects' },
  { word: 'saw', hint: 'Cai cua', category: 'objects' },
  { word: 'scale', hint: 'Can / Vay', category: 'objects' },
  { word: 'scissors', hint: 'Cai keo', category: 'objects' },
  { word: 'shovel', hint: 'Cai xeng', category: 'objects' },
  { word: 'silk', hint: 'Lua', category: 'objects' },
  { word: 'sink', hint: 'Bon rua', category: 'objects' },
  { word: 'sofa', hint: 'Ghe sofa', category: 'objects' },
  { word: 'spear', hint: 'Ngon giao', category: 'objects' },
  { word: 'spoon', hint: 'Cai thia', category: 'objects' },
  { word: 'stamp', hint: 'Con tem', category: 'objects' },
  { word: 'statue', hint: 'Buc tuong', category: 'objects' },
  { word: 'steel', hint: 'Thep', category: 'objects' },
  { word: 'stove', hint: 'Bep lo', category: 'objects' },
  { word: 'straw', hint: 'Ong hut / Rom', category: 'objects' },
  { word: 'sword', hint: 'Thanh kiem', category: 'objects' },
  { word: 'table', hint: 'Cai ban', category: 'objects' },
  { word: 'tap', hint: 'Voi nuoc', category: 'objects' },
  { word: 'textbook', hint: 'Sach giao khoa', category: 'objects' },
  { word: 'ticket', hint: 'Ve', category: 'objects' },
  { word: 'tissue', hint: 'Khan giay', category: 'objects' },
  { word: 'towel', hint: 'Khan tam', category: 'objects' },
  { word: 'toy', hint: 'Do choi', category: 'objects' },
  { word: 'trap', hint: 'Cai bay', category: 'objects' },
  { word: 'tray', hint: 'Cai khay', category: 'objects' },
  { word: 'treasure', hint: 'Kho bau', category: 'objects' },
  { word: 'trophy', hint: 'Cup / Giai', category: 'objects' },
  { word: 'vase', hint: 'Binh hoa', category: 'objects' },
  { word: 'web', hint: 'Mang nhen', category: 'objects' },
  { word: 'well', hint: 'Gieng nuoc', category: 'objects' },
  { word: 'wheel', hint: 'Banh xe', category: 'objects' },
  { word: 'window', hint: 'Cua so', category: 'objects' },
  { word: 'zip', hint: 'Khoa keo', category: 'objects' },

  // ── Places & Buildings ──
  { word: 'airport', hint: 'San bay', category: 'places' },
  { word: 'aquarium', hint: 'Be ca', category: 'places' },
  { word: 'bakery', hint: 'Tiem banh', category: 'places' },
  { word: 'balcony', hint: 'Ban cong', category: 'places' },
  { word: 'bathroom', hint: 'Phong tam', category: 'places' },
  { word: 'bedroom', hint: 'Phong ngu', category: 'places' },
  { word: 'boat', hint: 'Chiec thuyen', category: 'places' },
  { word: 'bridge', hint: 'Cay cau', category: 'places' },
  { word: 'building', hint: 'Toa nha', category: 'places' },
  { word: 'bus', hint: 'Xe buyt', category: 'places' },
  { word: 'cabin', hint: 'Can choi', category: 'places' },
  { word: 'car', hint: 'Xe o to', category: 'places' },
  { word: 'castle', hint: 'Lau dai', category: 'places' },
  { word: 'cave', hint: 'Hang dong', category: 'places' },
  { word: 'ceiling', hint: 'Tran nha', category: 'places' },
  { word: 'circus', hint: 'Rap xiec', category: 'places' },
  { word: 'classroom', hint: 'Lop hoc', category: 'places' },
  { word: 'country', hint: 'Dat nuoc', category: 'places' },
  { word: 'dam', hint: 'Dap nuoc', category: 'places' },
  { word: 'factory', hint: 'Nha may', category: 'places' },
  { word: 'farm', hint: 'Nong trai', category: 'places' },
  { word: 'fence', hint: 'Hang rao', category: 'places' },
  { word: 'harbor', hint: 'Ben cang', category: 'places' },
  { word: 'hill', hint: 'Ngon doi', category: 'places' },
  { word: 'hospital', hint: 'Benh vien', category: 'places' },
  { word: 'hut', hint: 'Tup leu', category: 'places' },
  { word: 'kitchen', hint: 'Nha bep', category: 'places' },
  { word: 'library', hint: 'Thu vien', category: 'places' },
  { word: 'market', hint: 'Cho', category: 'places' },
  { word: 'park', hint: 'Cong vien', category: 'places' },
  { word: 'parking', hint: 'Bai do xe', category: 'places' },
  { word: 'plane', hint: 'May bay', category: 'places' },
  { word: 'playground', hint: 'San choi', category: 'places' },
  { word: 'pyramid', hint: 'Kim tu thap', category: 'places' },
  { word: 'road', hint: 'Con duong', category: 'places' },
  { word: 'roof', hint: 'Mai nha', category: 'places' },
  { word: 'school', hint: 'Truong hoc', category: 'places' },
  { word: 'ship', hint: 'Con tau', category: 'places' },
  { word: 'stadium', hint: 'San van dong', category: 'places' },
  { word: 'stage', hint: 'San khau', category: 'places' },
  { word: 'stair', hint: 'Bac thang', category: 'places' },
  { word: 'street', hint: 'Duong pho', category: 'places' },
  { word: 'temple', hint: 'Ngoi den', category: 'places' },
  { word: 'tower', hint: 'Thap', category: 'places' },
  { word: 'train', hint: 'Tau hoa', category: 'places' },
  { word: 'truck', hint: 'Xe tai', category: 'places' },
  { word: 'van', hint: 'Xe van', category: 'places' },
  { word: 'vault', hint: 'Ham', category: 'places' },
  { word: 'village', hint: 'Ngoi lang', category: 'places' },
  { word: 'wall', hint: 'Buc tuong', category: 'places' },

  // ── People & Family ──
  { word: 'alien', hint: 'Nguoi ngoai hanh tinh', category: 'people' },
  { word: 'angel', hint: 'Thien than', category: 'people' },
  { word: 'barber', hint: 'Tho cat toc', category: 'people' },
  { word: 'brother', hint: 'Anh/em trai', category: 'people' },
  { word: 'captain', hint: 'Thuyen truong', category: 'people' },
  { word: 'champion', hint: 'Nha vo dich', category: 'people' },
  { word: 'chef', hint: 'Dau bep', category: 'people' },
  { word: 'child', hint: 'Dua tre', category: 'people' },
  { word: 'demon', hint: 'Quy', category: 'people' },
  { word: 'dentist', hint: 'Nha si', category: 'people' },
  { word: 'doctor', hint: 'Bac si', category: 'people' },
  { word: 'driver', hint: 'Tai xe', category: 'people' },
  { word: 'fairy', hint: 'Nang tien', category: 'people' },
  { word: 'family', hint: 'Gia dinh', category: 'people' },
  { word: 'farmer', hint: 'Nong dan', category: 'people' },
  { word: 'father', hint: 'Bo', category: 'people' },
  { word: 'fireman', hint: 'Linh cuu hoa', category: 'people' },
  { word: 'friend', hint: 'Ban be', category: 'people' },
  { word: 'gentleman', hint: 'Quy ong', category: 'people' },
  { word: 'ghost', hint: 'Con ma', category: 'people' },
  { word: 'giant', hint: 'Nguoi khong lo', category: 'people' },
  { word: 'grandma', hint: 'Ba', category: 'people' },
  { word: 'grandpa', hint: 'Ong', category: 'people' },
  { word: 'guard', hint: 'Bao ve', category: 'people' },
  { word: 'guide', hint: 'Huong dan vien', category: 'people' },
  { word: 'hero', hint: 'Anh hung', category: 'people' },
  { word: 'husband', hint: 'Chong', category: 'people' },
  { word: 'king', hint: 'Vua', category: 'people' },
  { word: 'knight', hint: 'Hiep si', category: 'people' },
  { word: 'monster', hint: 'Quai vat', category: 'people' },
  { word: 'mother', hint: 'Me', category: 'people' },
  { word: 'neighbor', hint: 'Hang xom', category: 'people' },
  { word: 'painter', hint: 'Hoa si', category: 'people' },
  { word: 'people', hint: 'Moi nguoi', category: 'people' },
  { word: 'pirate', hint: 'Cuop bien', category: 'people' },
  { word: 'police', hint: 'Canh sat', category: 'people' },
  { word: 'princess', hint: 'Cong chua', category: 'people' },
  { word: 'pupil', hint: 'Hoc tro', category: 'people' },
  { word: 'queen', hint: 'Nu hoang', category: 'people' },
  { word: 'rival', hint: 'Doi thu', category: 'people' },
  { word: 'singer', hint: 'Ca si', category: 'people' },
  { word: 'sister', hint: 'Chi/em gai', category: 'people' },
  { word: 'soldier', hint: 'Nguoi linh', category: 'people' },
  { word: 'student', hint: 'Hoc sinh', category: 'people' },
  { word: 'teacher', hint: 'Giao vien', category: 'people' },
  { word: 'tourist', hint: 'Du khach', category: 'people' },
  { word: 'vampire', hint: 'Ma ca rong', category: 'people' },
  { word: 'vet', hint: 'Bac si thu y', category: 'people' },
  { word: 'witch', hint: 'Phu thuy', category: 'people' },

  // ── Actions & Verbs ──
  { word: 'blink', hint: 'Chop mat', category: 'actions' },
  { word: 'catch', hint: 'Bat', category: 'actions' },
  { word: 'chase', hint: 'Duoi theo', category: 'actions' },
  { word: 'clean', hint: 'Sach se', category: 'actions' },
  { word: 'climb', hint: 'Leo treo', category: 'actions' },
  { word: 'cook', hint: 'Nau an', category: 'actions' },
  { word: 'count', hint: 'Dem', category: 'actions' },
  { word: 'crash', hint: 'Va cham', category: 'actions' },
  { word: 'crush', hint: 'Nghien nat', category: 'actions' },
  { word: 'dance', hint: 'Nhay mua', category: 'actions' },
  { word: 'dive', hint: 'Lan', category: 'actions' },
  { word: 'draw', hint: 'Ve', category: 'actions' },
  { word: 'exercise', hint: 'Bai tap', category: 'actions' },
  { word: 'float', hint: 'Noi', category: 'actions' },
  { word: 'flying', hint: 'Bay', category: 'actions' },
  { word: 'glow', hint: 'Phat sang', category: 'actions' },
  { word: 'guess', hint: 'Doan', category: 'actions' },
  { word: 'hop', hint: 'Nhay lo co', category: 'actions' },
  { word: 'hug', hint: 'Om', category: 'actions' },
  { word: 'jump', hint: 'Nhay', category: 'actions' },
  { word: 'kneel', hint: 'Quy', category: 'actions' },
  { word: 'laugh', hint: 'Cuoi', category: 'actions' },
  { word: 'listen', hint: 'Lang nghe', category: 'actions' },
  { word: 'mix', hint: 'Tron', category: 'actions' },
  { word: 'nap', hint: 'Giac ngu ngan', category: 'actions' },
  { word: 'painting', hint: 'Buc tranh', category: 'actions' },
  { word: 'play', hint: 'Choi', category: 'actions' },
  { word: 'press', hint: 'An / Ep', category: 'actions' },
  { word: 'read', hint: 'Doc', category: 'actions' },
  { word: 'row', hint: 'Cheo thuyen', category: 'actions' },
  { word: 'run', hint: 'Chay', category: 'actions' },
  { word: 'running', hint: 'Chay bo', category: 'actions' },
  { word: 'shopping', hint: 'Mua sam', category: 'actions' },
  { word: 'sing', hint: 'Hat', category: 'actions' },
  { word: 'sip', hint: 'Nhap (nuoc)', category: 'actions' },
  { word: 'skating', hint: 'Truot bang', category: 'actions' },
  { word: 'sleep', hint: 'Ngu', category: 'actions' },
  { word: 'sleeping', hint: 'Dang ngu', category: 'actions' },
  { word: 'smile', hint: 'Nu cuoi', category: 'actions' },
  { word: 'speak', hint: 'Noi', category: 'actions' },
  { word: 'spray', hint: 'Phun / Xit', category: 'actions' },
  { word: 'stare', hint: 'Nhin cham cham', category: 'actions' },
  { word: 'surf', hint: 'Luot song', category: 'actions' },
  { word: 'swim', hint: 'Boi', category: 'actions' },
  { word: 'swimming', hint: 'Boi loi', category: 'actions' },
  { word: 'swing', hint: 'Xich du', category: 'actions' },
  { word: 'talk', hint: 'Noi chuyen', category: 'actions' },
  { word: 'think', hint: 'Suy nghi', category: 'actions' },
  { word: 'throw', hint: 'Nem', category: 'actions' },
  { word: 'travel', hint: 'Du lich', category: 'actions' },
  { word: 'walk', hint: 'Di bo', category: 'actions' },
  { word: 'wrap', hint: 'Goi / Boc', category: 'actions' },
  { word: 'write', hint: 'Viet', category: 'actions' },
  { word: 'yawn', hint: 'Ngap', category: 'actions' },

  // ── Emotions & Adjectives ──
  { word: 'angry', hint: 'Tuc gian', category: 'feelings' },
  { word: 'blank', hint: 'Trong', category: 'feelings' },
  { word: 'brave', hint: 'Dung cam', category: 'feelings' },
  { word: 'cloudy', hint: 'Nhieu may', category: 'feelings' },
  { word: 'dream', hint: 'Giac mo', category: 'feelings' },
  { word: 'ease', hint: 'De dang', category: 'feelings' },
  { word: 'frozen', hint: 'Dong lanh', category: 'feelings' },
  { word: 'gentle', hint: 'Diu dang', category: 'feelings' },
  { word: 'happy', hint: 'Vui ve', category: 'feelings' },
  { word: 'heavy', hint: 'Nang', category: 'feelings' },
  { word: 'hungry', hint: 'Doi', category: 'feelings' },
  { word: 'love', hint: 'Tinh yeu', category: 'feelings' },
  { word: 'pride', hint: 'Niem tu hao', category: 'feelings' },
  { word: 'quiet', hint: 'Yen lang', category: 'feelings' },
  { word: 'round', hint: 'Tron', category: 'feelings' },
  { word: 'salty', hint: 'Man', category: 'feelings' },
  { word: 'scared', hint: 'So hai', category: 'feelings' },
  { word: 'sharp', hint: 'Sac / Nhon', category: 'feelings' },
  { word: 'silence', hint: 'Su im lang', category: 'feelings' },
  { word: 'smart', hint: 'Thong minh', category: 'feelings' },
  { word: 'snowy', hint: 'Co tuyet', category: 'feelings' },
  { word: 'steep', hint: 'Doc', category: 'feelings' },
  { word: 'stormy', hint: 'Bao', category: 'feelings' },
  { word: 'strong', hint: 'Manh me', category: 'feelings' },
  { word: 'sunny', hint: 'Nang', category: 'feelings' },
  { word: 'sweet', hint: 'Ngot', category: 'feelings' },
  { word: 'tired', hint: 'Met moi', category: 'feelings' },

  // ── Time & Events ──
  { word: 'alarm', hint: 'Bao thuc', category: 'time' },
  { word: 'birthday', hint: 'Sinh nhat', category: 'time' },
  { word: 'century', hint: 'The ky', category: 'time' },
  { word: 'chapter', hint: 'Chuong', category: 'time' },
  { word: 'concert', hint: 'Buoi hoa nhac', category: 'time' },
  { word: 'evening', hint: 'Buoi toi', category: 'time' },
  { word: 'holiday', hint: 'Ngay le', category: 'time' },
  { word: 'morning', hint: 'Buoi sang', category: 'time' },
  { word: 'night', hint: 'Ban dem', category: 'time' },
  { word: 'story', hint: 'Cau chuyen', category: 'time' },
  { word: 'tonight', hint: 'Toi nay', category: 'time' },
  { word: 'weekend', hint: 'Cuoi tuan', category: 'time' },
  { word: 'world', hint: 'The gioi', category: 'time' },

  // ── School & Learning ──
  { word: 'address', hint: 'Dia chi', category: 'school' },
  { word: 'alphabet', hint: 'Bang chu cai', category: 'school' },
  { word: 'circle', hint: 'Hinh tron', category: 'school' },
  { word: 'display', hint: 'Man hinh', category: 'school' },
  { word: 'geography', hint: 'Dia ly', category: 'school' },
  { word: 'language', hint: 'Ngon ngu', category: 'school' },
  { word: 'letter', hint: 'Chu cai', category: 'school' },
  { word: 'magic', hint: 'Phep thuat', category: 'school' },
  { word: 'music', hint: 'Am nhac', category: 'school' },
  { word: 'number', hint: 'Con so', category: 'school' },
  { word: 'picture', hint: 'Buc tranh', category: 'school' },
  { word: 'proof', hint: 'Bang chung', category: 'school' },
  { word: 'question', hint: 'Cau hoi', category: 'school' },
  { word: 'quiz', hint: 'Cau do', category: 'school' },
  { word: 'rectangle', hint: 'Hinh chu nhat', category: 'school' },
  { word: 'scope', hint: 'Pham vi', category: 'school' },
  { word: 'square', hint: 'Hinh vuong', category: 'school' },
  { word: 'triangle', hint: 'Hinh tam giac', category: 'school' },

  // ── Sports & Games ──
  { word: 'ballet', hint: 'Mua ba le', category: 'sports' },
  { word: 'chess', hint: 'Co vua', category: 'sports' },
  { word: 'gift', hint: 'Qua tang', category: 'sports' },
  { word: 'motor', hint: 'Dong co', category: 'sports' },
  { word: 'snowman', hint: 'Nguoi tuyet', category: 'sports' },
  { word: 'soccer', hint: 'Bong da', category: 'sports' },
  { word: 'squad', hint: 'Doi', category: 'sports' },
  { word: 'tennis', hint: 'Quan vot', category: 'sports' },
  { word: 'yoga', hint: 'Yoga', category: 'sports' },

  // ── Miscellaneous ──
  { word: 'club', hint: 'Cau lac bo', category: 'misc' },
  { word: 'gap', hint: 'Khoang trong', category: 'misc' },
  { word: 'hobbit', hint: 'Nguoi lun Hobbit', category: 'misc' },
  { word: 'radar', hint: 'Ra-da', category: 'misc' },
  { word: 'rural', hint: 'Nong thon', category: 'misc' },
  { word: 'scent', hint: 'Mui huong', category: 'misc' },
  { word: 'stain', hint: 'Vet ban', category: 'misc' },
  { word: 'strip', hint: 'Dai / Thanh', category: 'misc' },
  { word: 'zone', hint: 'Khu vuc', category: 'misc' },
  { word: 'zoom', hint: 'Phong to', category: 'misc' },

  // ── Transport ──
  { word: 'bicycle', hint: 'Xe dap', category: 'transport' },
  { word: 'helicopter', hint: 'Truc thang', category: 'transport' },
  { word: 'subway', hint: 'Tau dien ngam', category: 'transport' },
  { word: 'motorcycle', hint: 'Xe may', category: 'transport' },
  { word: 'ambulance', hint: 'Xe cuu thuong', category: 'transport' },
  { word: 'taxi', hint: 'Xe taxi', category: 'transport' },
  { word: 'tractor', hint: 'May keo', category: 'transport' },
  { word: 'canoe', hint: 'Thuyen doc moc', category: 'transport' },

  // ── Furniture ──
  { word: 'shelf', hint: 'Ke / Gia', category: 'furniture' },
  { word: 'drawer', hint: 'Ngan keo', category: 'furniture' },
  { word: 'curtain', hint: 'Rem cua', category: 'furniture' },
  { word: 'wardrobe', hint: 'Tu quan ao', category: 'furniture' },
  { word: 'cushion', hint: 'Goi dem', category: 'furniture' },
  { word: 'bookcase', hint: 'Tu sach', category: 'furniture' },
  { word: 'mattress', hint: 'Nem', category: 'furniture' },
  { word: 'couch', hint: 'Ghe dai', category: 'furniture' },
  { word: 'desk', hint: 'Ban lam viec', category: 'furniture' },
  { word: 'stool', hint: 'Ghe dau', category: 'furniture' },

  // ── Weather ──
  { word: 'rainy', hint: 'Co mua', category: 'weather' },
  { word: 'windy', hint: 'Co gio', category: 'weather' },
  { word: 'foggy', hint: 'Co suong mu', category: 'weather' },
  { word: 'humid', hint: 'Am uot', category: 'weather' },
  { word: 'breeze', hint: 'Gio nhe', category: 'weather' },
  { word: 'lightning', hint: 'Tia chop', category: 'weather' },
  { word: 'drought', hint: 'Han han', category: 'weather' },
  { word: 'typhoon', hint: 'Bao', category: 'weather' },

  // ── Numbers & Math ──
  { word: 'zero', hint: 'So khong', category: 'numbers' },
  { word: 'half', hint: 'Mot nua', category: 'numbers' },
  { word: 'double', hint: 'Gap doi', category: 'numbers' },
  { word: 'dozen', hint: 'Ta (12)', category: 'numbers' },
  { word: 'hundred', hint: 'Mot tram', category: 'numbers' },
  { word: 'thousand', hint: 'Mot ngan', category: 'numbers' },
  { word: 'million', hint: 'Mot trieu', category: 'numbers' },
  { word: 'minus', hint: 'Tru', category: 'numbers' },
  { word: 'total', hint: 'Tong cong', category: 'numbers' },
  { word: 'equal', hint: 'Bang nhau', category: 'numbers' },

  // ── Shapes ──
  { word: 'oval', hint: 'Hinh bau duc', category: 'shapes' },
  { word: 'sphere', hint: 'Hinh cau', category: 'shapes' },
  { word: 'cone', hint: 'Hinh non', category: 'shapes' },
  { word: 'cylinder', hint: 'Hinh tru', category: 'shapes' },
  { word: 'pyramid', hint: 'Hinh chop', category: 'shapes' },
  { word: 'arrow', hint: 'Hinh mui ten', category: 'shapes' },
  { word: 'star', hint: 'Hinh ngoi sao', category: 'shapes' },
  { word: 'cross', hint: 'Hinh chu thap', category: 'shapes' },

  // ── Music & Instruments ──
  { word: 'violin', hint: 'Dan vi cam', category: 'music' },
  { word: 'trumpet', hint: 'Ken trumpet', category: 'music' },
  { word: 'flute', hint: 'Sang / Ong sao', category: 'music' },
  { word: 'melody', hint: 'Giai dieu', category: 'music' },
  { word: 'lyrics', hint: 'Loi bai hat', category: 'music' },
  { word: 'harmony', hint: 'Hoa am', category: 'music' },

  // ── Holidays & Festivals ──
  { word: 'christmas', hint: 'Le Giang Sinh', category: 'holidays' },
  { word: 'easter', hint: 'Le Phuc Sinh', category: 'holidays' },
  { word: 'halloween', hint: 'Le Halloween', category: 'holidays' },
  { word: 'costume', hint: 'Trang phuc', category: 'holidays' },
  { word: 'parade', hint: 'Dieu hanh', category: 'holidays' },
  { word: 'lantern', hint: 'Den long', category: 'holidays' },
  { word: 'festival', hint: 'Le hoi', category: 'holidays' },
  { word: 'carnival', hint: 'Hoi cho', category: 'holidays' },
  { word: 'balloon', hint: 'Bong bay', category: 'holidays' },
  { word: 'ribbon', hint: 'Dai ruy bang', category: 'holidays' },

  // ── Ocean & Sea Life ──
  { word: 'seaweed', hint: 'Rong bien', category: 'ocean' },
  { word: 'lighthouse', hint: 'Ngon hai dang', category: 'ocean' },
  { word: 'submarine', hint: 'Tau ngam', category: 'ocean' },
  { word: 'iceberg', hint: 'Tang bang', category: 'ocean' },
  { word: 'diver', hint: 'Tho lan', category: 'ocean' },
  { word: 'seahorse', hint: 'Ca ngua', category: 'ocean' },
  { word: 'clam', hint: 'Con ngao', category: 'ocean' },
  { word: 'squid', hint: 'Con muc', category: 'ocean' },
  { word: 'tide', hint: 'Thuy trieu', category: 'ocean' },

  // ── Insects ──
  { word: 'beetle', hint: 'Bo canh cung', category: 'insects' },
  { word: 'mosquito', hint: 'Con muoi', category: 'insects' },
  { word: 'cricket', hint: 'Con de', category: 'insects' },
  { word: 'grasshopper', hint: 'Chau chau', category: 'insects' },
  { word: 'ladybug', hint: 'Bo rua', category: 'insects' },
  { word: 'caterpillar', hint: 'Sau buom', category: 'insects' },
  { word: 'firefly', hint: 'Dom dom', category: 'insects' },
  { word: 'cockroach', hint: 'Con gian', category: 'insects' },

  // ── Kitchen ──
  { word: 'apron', hint: 'Tap de', category: 'kitchen' },
  { word: 'blender', hint: 'May xay sinh to', category: 'kitchen' },
  { word: 'toaster', hint: 'May nuong banh mi', category: 'kitchen' },
  { word: 'microwave', hint: 'Lo vi song', category: 'kitchen' },
  { word: 'freezer', hint: 'Tu dong da', category: 'kitchen' },
  { word: 'chopstick', hint: 'Dua (an)', category: 'kitchen' },

  // ── Emotions ──
  { word: 'nervous', hint: 'Lo lang', category: 'emotions' },
  { word: 'excited', hint: 'Hao hung', category: 'emotions' },
  { word: 'lonely', hint: 'Co don', category: 'emotions' },
  { word: 'curious', hint: 'To mo', category: 'emotions' },
  { word: 'proud', hint: 'Tu hao', category: 'emotions' },
  { word: 'jealous', hint: 'Ghen ti', category: 'emotions' },
  { word: 'grateful', hint: 'Biet on', category: 'emotions' },
  { word: 'confused', hint: 'Boi roi', category: 'emotions' },
  { word: 'cheerful', hint: 'Vui tuoi', category: 'emotions' },
  { word: 'grumpy', hint: 'Cau kinh', category: 'emotions' },

  // ── Greetings & Phrases ──
  { word: 'hello', hint: 'Xin chao', category: 'greetings' },
  { word: 'goodbye', hint: 'Tam biet', category: 'greetings' },
  { word: 'please', hint: 'Lam on', category: 'greetings' },
  { word: 'sorry', hint: 'Xin loi', category: 'greetings' },
  { word: 'thanks', hint: 'Cam on', category: 'greetings' },
  { word: 'welcome', hint: 'Chao mung', category: 'greetings' },
  { word: 'excuse', hint: 'Xin phep', category: 'greetings' },
  { word: 'cheers', hint: 'Chuc mung', category: 'greetings' },
  { word: 'congrats', hint: 'Xin chuc mung', category: 'greetings' },
  { word: 'farewell', hint: 'Chia tay', category: 'greetings' },

]

export default WORD_BANK
