-- ============================================================
-- Pet Word Bank Migration
-- Run this in your Supabase SQL editor
-- ============================================================

CREATE TABLE IF NOT EXISTS public.pet_word_bank (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  word text NOT NULL,
  hint text NOT NULL,
  difficulty text NOT NULL DEFAULT 'easy'
    CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
  min_level integer NOT NULL DEFAULT 1,
  image_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pet_word_bank_pkey PRIMARY KEY (id),
  CONSTRAINT pet_word_bank_word_key UNIQUE (word)
);

-- Enable RLS
ALTER TABLE public.pet_word_bank ENABLE ROW LEVEL SECURITY;

-- Admins can do anything
CREATE POLICY "Admins can manage word bank"
  ON public.pet_word_bank FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'));

-- All authenticated users can read active words
CREATE POLICY "Users can read active words"
  ON public.pet_word_bank FOR SELECT
  USING (is_active = true);

-- ── Seed Data ────────────────────────────────────────────────
-- difficulty: easy=3-4 letters, medium=5-6 letters, hard=7+ letters
-- min_level: 1 (3-letter), 2 (4-letter), 4 (5-letter), 6 (6-letter), 8 (7+letter)

INSERT INTO public.pet_word_bank (word, hint, difficulty, min_level) VALUES
-- 3 letters (easy, level 1)
('cat', 'Con mèo', 'easy', 1),
('dog', 'Con chó', 'easy', 1),
('sun', 'Mặt trời', 'easy', 1),
('run', 'Chạy', 'easy', 1),
('egg', 'Quả trứng', 'easy', 1),
('red', 'Màu đỏ', 'easy', 1),
('hat', 'Cái mũ', 'easy', 1),
('cup', 'Cái cốc', 'easy', 1),
('pen', 'Cái bút', 'easy', 1),
('box', 'Cái hộp', 'easy', 1),
('bag', 'Cái túi', 'easy', 1),
('bus', 'Xe buýt', 'easy', 1),
('car', 'Xe ô tô', 'easy', 1),
('bed', 'Cái giường', 'easy', 1),
('cow', 'Con bò', 'easy', 1),
('pig', 'Con lợn', 'easy', 1),
('ant', 'Con kiến', 'easy', 1),
('bee', 'Con ong', 'easy', 1),
('fly', 'Con ruồi', 'easy', 1),
('map', 'Bản đồ', 'easy', 1),
('ice', 'Đá / Băng', 'easy', 1),
('sky', 'Bầu trời', 'easy', 1),
('sea', 'Biển', 'easy', 1),
('toy', 'Đồ chơi', 'easy', 1),
('key', 'Chìa khóa', 'easy', 1),
('ear', 'Cái tai', 'easy', 1),
('eye', 'Con mắt', 'easy', 1),
('leg', 'Cái chân', 'easy', 1),
('arm', 'Cánh tay', 'easy', 1),
('fan', 'Cái quạt', 'easy', 1),
('fox', 'Con cáo', 'easy', 1),
('owl', 'Con cú', 'easy', 1),
('bat', 'Con dơi', 'easy', 1),
('nut', 'Hạt', 'easy', 1),
('pie', 'Bánh nướng', 'easy', 1),
('pot', 'Cái nồi', 'easy', 1),
('jar', 'Cái lọ', 'easy', 1),
('net', 'Cái lưới', 'easy', 1),
('log', 'Khúc gỗ', 'easy', 1),
('mud', 'Bùn', 'easy', 1),
('fur', 'Lông thú', 'easy', 1),
('gem', 'Viên ngọc', 'easy', 1),
('ink', 'Mực', 'easy', 1),
('jam', 'Mứt', 'easy', 1),
('jaw', 'Hàm', 'easy', 1),
('lip', 'Môi', 'easy', 1),
('rug', 'Tấm thảm', 'easy', 1),
('tap', 'Vòi nước', 'easy', 1),
('van', 'Xe van', 'easy', 1),
('vet', 'Bác sĩ thú y', 'easy', 1),
('web', 'Mạng nhện', 'easy', 1),
('zip', 'Khóa kéo', 'easy', 1),
('hop', 'Nhảy lò cò', 'easy', 1),
('hug', 'Ôm', 'easy', 1),
('mix', 'Trộn', 'easy', 1),
('nap', 'Giấc ngủ ngắn', 'easy', 1),
('sip', 'Nhấp (nước)', 'easy', 1),
('dew', 'Sương', 'easy', 1),
('fog', 'Sương mù', 'easy', 1),
('oak', 'Cây sồi', 'easy', 1),
('rib', 'Xương sườn', 'easy', 1),
('row', 'Hàng / Dãy', 'easy', 1),
('saw', 'Cái cưa', 'easy', 1),
('fig', 'Quả sung', 'easy', 1),
('yam', 'Khoai mỡ', 'easy', 1),
('bow', 'Cái cung', 'easy', 1),
('axe', 'Cái rìu', 'easy', 1),
('fin', 'Vây cá', 'easy', 1),
('gap', 'Khoảng trống', 'easy', 1),
('hen', 'Gà mái', 'easy', 1),
('ram', 'Cừu đực', 'easy', 1),
('cub', 'Thú con', 'easy', 1),
('dam', 'Đập nước', 'easy', 1),
('bay', 'Vịnh', 'easy', 1),
('hut', 'Túp lều', 'easy', 1),
-- 4 letters (easy, level 2)
('book', 'Quyển sách', 'easy', 2),
('fish', 'Con cá', 'easy', 2),
('bird', 'Con chim', 'easy', 2),
('tree', 'Cái cây', 'easy', 2),
('rain', 'Mưa', 'easy', 2),
('star', 'Ngôi sao', 'easy', 2),
('cake', 'Bánh', 'easy', 2),
('door', 'Cái cửa', 'easy', 2),
('hand', 'Bàn tay', 'easy', 2),
('moon', 'Mặt trăng', 'easy', 2),
('frog', 'Con ếch', 'easy', 2),
('duck', 'Con vịt', 'easy', 2),
('bear', 'Con gấu', 'easy', 2),
('deer', 'Con hươu', 'easy', 2),
('lion', 'Con sư tử', 'easy', 2),
('wolf', 'Con sói', 'easy', 2),
('goat', 'Con dê', 'easy', 2),
('lamp', 'Cái đèn', 'easy', 2),
('ball', 'Quả bóng', 'easy', 2),
('rice', 'Gạo / Cơm', 'easy', 2),
('milk', 'Sữa', 'easy', 2),
('soup', 'Súp / Canh', 'easy', 2),
('meat', 'Thịt', 'easy', 2),
('salt', 'Muối', 'easy', 2),
('shoe', 'Giày', 'easy', 2),
('sock', 'Tất / Vớ', 'easy', 2),
('coat', 'Áo khoác', 'easy', 2),
('ring', 'Chiếc nhẫn', 'easy', 2),
('bell', 'Cái chuông', 'easy', 2),
('drum', 'Cái trống', 'easy', 2),
('flag', 'Lá cờ', 'easy', 2),
('ship', 'Con tàu', 'easy', 2),
('boat', 'Chiếc thuyền', 'easy', 2),
('wind', 'Gió', 'easy', 2),
('fire', 'Lửa', 'easy', 2),
('snow', 'Tuyết', 'easy', 2),
('sand', 'Cát', 'easy', 2),
('gold', 'Vàng', 'easy', 2),
('king', 'Vua', 'easy', 2),
('nose', 'Cái mũi', 'easy', 2),
('face', 'Khuôn mặt', 'easy', 2),
('foot', 'Bàn chân', 'easy', 2),
('hair', 'Tóc', 'easy', 2),
('neck', 'Cổ', 'easy', 2),
('blue', 'Màu xanh dương', 'easy', 2),
('pink', 'Màu hồng', 'easy', 2),
('gray', 'Màu xám', 'easy', 2),
('love', 'Tình yêu', 'easy', 2),
('sing', 'Hát', 'easy', 2),
('jump', 'Nhảy', 'easy', 2),
('swim', 'Bơi', 'easy', 2),
('cook', 'Nấu ăn', 'easy', 2),
('read', 'Đọc', 'easy', 2),
('draw', 'Vẽ', 'easy', 2),
('play', 'Chơi', 'easy', 2),
('walk', 'Đi bộ', 'easy', 2),
('talk', 'Nói chuyện', 'easy', 2),
('gift', 'Quà tặng', 'easy', 2),
('park', 'Công viên', 'easy', 2),
('road', 'Con đường', 'easy', 2),
('wall', 'Bức tường', 'easy', 2),
('roof', 'Mái nhà', 'easy', 2),
('farm', 'Nông trại', 'easy', 2),
('lake', 'Hồ nước', 'easy', 2),
('leaf', 'Chiếc lá', 'easy', 2),
('seed', 'Hạt giống', 'easy', 2),
('rose', 'Hoa hồng', 'easy', 2),
('nest', 'Tổ chim', 'easy', 2),
('tail', 'Cái đuôi', 'easy', 2),
('wing', 'Cánh (chim)', 'easy', 2),
('bone', 'Xương', 'easy', 2),
('crab', 'Con cua', 'easy', 2),
('worm', 'Con sâu', 'easy', 2),
('bean', 'Hạt đậu', 'easy', 2),
('cave', 'Hang động', 'easy', 2),
('chef', 'Đầu bếp', 'easy', 2),
('chin', 'Cằm', 'easy', 2),
('clay', 'Đất sét', 'easy', 2),
('club', 'Câu lạc bộ', 'easy', 2),
('coal', 'Than', 'easy', 2),
('coin', 'Đồng xu', 'easy', 2),
('corn', 'Ngô / Bắp', 'easy', 2),
('crow', 'Con quạ', 'easy', 2),
('cube', 'Hình lập phương', 'easy', 2),
('dive', 'Lặn', 'easy', 2),
('dove', 'Chim bồ câu', 'easy', 2),
('dusk', 'Hoàng hôn', 'easy', 2),
('dust', 'Bụi', 'easy', 2),
('ease', 'Dễ dàng', 'easy', 2),
('fork', 'Cái nĩa', 'easy', 2),
('fuel', 'Nhiên liệu', 'easy', 2),
('gate', 'Cổng', 'easy', 2),
('gear', 'Bánh răng', 'easy', 2),
('glow', 'Phát sáng', 'easy', 2),
('glue', 'Keo dán', 'easy', 2),
('hare', 'Thỏ rừng', 'easy', 2),
('hawk', 'Chim ưng', 'easy', 2),
('heel', 'Gót chân', 'easy', 2),
('hero', 'Anh hùng', 'easy', 2),
('hill', 'Ngọn đồi', 'easy', 2),
('hive', 'Tổ ong', 'easy', 2),
('horn', 'Sừng', 'easy', 2),
('iron', 'Sắt', 'easy', 2),
('kite', 'Con diều', 'easy', 2),
('knot', 'Nút thắt', 'easy', 2),
('lime', 'Quả chanh', 'easy', 2),
('nail', 'Cái đinh', 'easy', 2),
('oven', 'Lò nướng', 'easy', 2),
('pear', 'Quả lê', 'easy', 2),
('pond', 'Ao', 'easy', 2),
('quiz', 'Câu đố', 'easy', 2),
('rope', 'Dây thừng', 'easy', 2),
('ruby', 'Hồng ngọc', 'easy', 2),
('sail', 'Cánh buồm', 'easy', 2),
('silk', 'Lụa', 'easy', 2),
('sink', 'Bồn rửa', 'easy', 2),
('sofa', 'Ghế sofa', 'easy', 2),
('swan', 'Thiên nga', 'easy', 2),
('tomb', 'Ngôi mộ', 'easy', 2),
('tray', 'Cái khay', 'easy', 2),
('tuna', 'Cá ngừ', 'easy', 2),
('vase', 'Bình hoa', 'easy', 2),
('vest', 'Áo ghi lê', 'easy', 2),
('vine', 'Dây leo', 'easy', 2),
('well', 'Giếng nước', 'easy', 2),
('yawn', 'Ngáp', 'easy', 2),
('yoga', 'Yoga', 'easy', 2),
('zone', 'Khu vực', 'easy', 2),
('zoom', 'Phóng to', 'easy', 2),
('reef', 'Rạn san hô', 'easy', 2),
('seal', 'Hải cẩu', 'easy', 2),
('surf', 'Lướt sóng', 'easy', 2),
('trap', 'Cái bẫy', 'easy', 2),
('wrap', 'Gói / Bọc', 'easy', 2),
-- 5 letters (medium, level 4)
('apple', 'Quả táo', 'medium', 4),
('house', 'Ngôi nhà', 'medium', 4),
('water', 'Nước', 'medium', 4),
('smile', 'Nụ cười', 'medium', 4),
('table', 'Cái bàn', 'medium', 4),
('chair', 'Cái ghế', 'medium', 4),
('sleep', 'Ngủ', 'medium', 4),
('happy', 'Vui vẻ', 'medium', 4),
('music', 'Âm nhạc', 'medium', 4),
('dance', 'Nhảy múa', 'medium', 4),
('green', 'Màu xanh lá', 'medium', 4),
('bread', 'Bánh mì', 'medium', 4),
('tiger', 'Con hổ', 'medium', 4),
('cloud', 'Đám mây', 'medium', 4),
('light', 'Ánh sáng', 'medium', 4),
('horse', 'Con ngựa', 'medium', 4),
('mouse', 'Con chuột', 'medium', 4),
('snake', 'Con rắn', 'medium', 4),
('whale', 'Cá voi', 'medium', 4),
('shark', 'Cá mập', 'medium', 4),
('sheep', 'Con cừu', 'medium', 4),
('eagle', 'Đại bàng', 'medium', 4),
('camel', 'Con lạc đà', 'medium', 4),
('panda', 'Gấu trúc', 'medium', 4),
('grape', 'Quả nho', 'medium', 4),
('lemon', 'Quả chanh vàng', 'medium', 4),
('mango', 'Quả xoài', 'medium', 4),
('peach', 'Quả đào', 'medium', 4),
('melon', 'Quả dưa', 'medium', 4),
('onion', 'Củ hành', 'medium', 4),
('candy', 'Kẹo', 'medium', 4),
('juice', 'Nước ép', 'medium', 4),
('pizza', 'Bánh pizza', 'medium', 4),
('salad', 'Rau trộn', 'medium', 4),
('spoon', 'Cái thìa', 'medium', 4),
('knife', 'Con dao', 'medium', 4),
('plate', 'Cái đĩa', 'medium', 4),
('glass', 'Cái ly', 'medium', 4),
('clock', 'Đồng hồ', 'medium', 4),
('phone', 'Điện thoại', 'medium', 4),
('piano', 'Đàn piano', 'medium', 4),
('radio', 'Đài radio', 'medium', 4),
('brush', 'Bàn chải', 'medium', 4),
('towel', 'Khăn tắm', 'medium', 4),
('shirt', 'Áo sơ mi', 'medium', 4),
('skirt', 'Váy ngắn', 'medium', 4),
('dress', 'Váy dài', 'medium', 4),
('pants', 'Quần dài', 'medium', 4),
('scarf', 'Khăn quàng', 'medium', 4),
('queen', 'Nữ hoàng', 'medium', 4),
('angel', 'Thiên thần', 'medium', 4),
('heart', 'Trái tim', 'medium', 4),
('dream', 'Giấc mơ', 'medium', 4),
('story', 'Câu chuyện', 'medium', 4),
('color', 'Màu sắc', 'medium', 4),
('black', 'Màu đen', 'medium', 4),
('white', 'Màu trắng', 'medium', 4),
('brown', 'Màu nâu', 'medium', 4),
('mouth', 'Miệng', 'medium', 4),
('teeth', 'Răng', 'medium', 4),
('brain', 'Bộ não', 'medium', 4),
('blood', 'Máu', 'medium', 4),
('river', 'Dòng sông', 'medium', 4),
('ocean', 'Đại dương', 'medium', 4),
('earth', 'Trái đất', 'medium', 4),
('stone', 'Hòn đá', 'medium', 4),
('grass', 'Cỏ', 'medium', 4),
('field', 'Cánh đồng', 'medium', 4),
('beach', 'Bãi biển', 'medium', 4),
('train', 'Tàu hỏa', 'medium', 4),
('plane', 'Máy bay', 'medium', 4),
('truck', 'Xe tải', 'medium', 4),
('climb', 'Leo trèo', 'medium', 4),
('catch', 'Bắt', 'medium', 4),
('throw', 'Ném', 'medium', 4),
('write', 'Viết', 'medium', 4),
('think', 'Suy nghĩ', 'medium', 4),
('speak', 'Nói', 'medium', 4),
('laugh', 'Cười', 'medium', 4),
('clean', 'Sạch sẽ', 'medium', 4),
('quiet', 'Yên lặng', 'medium', 4),
('brave', 'Dũng cảm', 'medium', 4),
('smart', 'Thông minh', 'medium', 4),
('angry', 'Tức giận', 'medium', 4),
('tired', 'Mệt mỏi', 'medium', 4),
('sweet', 'Ngọt', 'medium', 4),
('salty', 'Mặn', 'medium', 4),
('round', 'Tròn', 'medium', 4),
('sharp', 'Sắc / Nhọn', 'medium', 4),
('heavy', 'Nặng', 'medium', 4),
('child', 'Đứa trẻ', 'medium', 4),
('world', 'Thế giới', 'medium', 4),
('night', 'Ban đêm', 'medium', 4),
('lunch', 'Bữa trưa', 'medium', 4),
('tower', 'Tháp', 'medium', 4),
('alarm', 'Báo thức', 'medium', 4),
('alien', 'Người ngoài hành tinh', 'medium', 4),
('ankle', 'Mắt cá chân', 'medium', 4),
('arrow', 'Mũi tên', 'medium', 4),
('badge', 'Huy hiệu', 'medium', 4),
('blank', 'Trống', 'medium', 4),
('blink', 'Chớp mắt', 'medium', 4),
('brick', 'Viên gạch', 'medium', 4),
('broom', 'Cái chổi', 'medium', 4),
('cabin', 'Căn chòi', 'medium', 4),
('chalk', 'Phấn viết', 'medium', 4),
('chase', 'Đuổi theo', 'medium', 4),
('cheek', 'Má', 'medium', 4),
('chess', 'Cờ vua', 'medium', 4),
('chest', 'Ngực / Rương', 'medium', 4),
('coast', 'Bờ biển', 'medium', 4),
('coral', 'San hô', 'medium', 4),
('couch', 'Ghế dài', 'medium', 4),
('count', 'Đếm', 'medium', 4),
('crash', 'Va chạm', 'medium', 4),
('crown', 'Vương miện', 'medium', 4),
('crush', 'Nghiền nát', 'medium', 4),
('demon', 'Quỷ', 'medium', 4),
('fairy', 'Nàng tiên', 'medium', 4),
('fence', 'Hàng rào', 'medium', 4),
('flame', 'Ngọn lửa', 'medium', 4),
('float', 'Nổi', 'medium', 4),
('flood', 'Lũ lụt', 'medium', 4),
('flour', 'Bột mì', 'medium', 4),
('fruit', 'Trái cây', 'medium', 4),
('ghost', 'Con ma', 'medium', 4),
('giant', 'Người khổng lồ', 'medium', 4),
('globe', 'Quả địa cầu', 'medium', 4),
('goose', 'Con ngỗng', 'medium', 4),
('guard', 'Bảo vệ', 'medium', 4),
('guess', 'Đoán', 'medium', 4),
('guide', 'Hướng dẫn viên', 'medium', 4),
('honey', 'Mật ong', 'medium', 4),
('jewel', 'Viên ngọc', 'medium', 4),
('kneel', 'Quỳ', 'medium', 4),
('leash', 'Dây xích', 'medium', 4),
('magic', 'Phép thuật', 'medium', 4),
('medal', 'Huy chương', 'medium', 4),
('metal', 'Kim loại', 'medium', 4),
('motor', 'Động cơ', 'medium', 4),
('olive', 'Quả ô liu', 'medium', 4),
('otter', 'Rái cá', 'medium', 4),
('paste', 'Hồ dán', 'medium', 4),
('pearl', 'Ngọc trai', 'medium', 4),
('pedal', 'Bàn đạp', 'medium', 4),
('penny', 'Đồng xu', 'medium', 4),
('press', 'Ấn / Ép', 'medium', 4),
('pride', 'Niềm tự hào', 'medium', 4),
('prize', 'Giải thưởng', 'medium', 4),
('proof', 'Bằng chứng', 'medium', 4),
('pupil', 'Học trò', 'medium', 4),
('radar', 'Ra-đa', 'medium', 4),
('rival', 'Đối thủ', 'medium', 4),
('robin', 'Chim cổ đỏ', 'medium', 4),
('rural', 'Nông thôn', 'medium', 4),
('sauce', 'Nước sốt', 'medium', 4),
('scale', 'Cân / Vảy', 'medium', 4),
('scent', 'Mùi hương', 'medium', 4),
('scope', 'Phạm vi', 'medium', 4),
('shell', 'Vỏ sò', 'medium', 4),
('shore', 'Bờ biển', 'medium', 4),
('skull', 'Hộp sọ', 'medium', 4),
('sloth', 'Con lười', 'medium', 4),
('snail', 'Con ốc sên', 'medium', 4),
('solar', 'Mặt trời', 'medium', 4),
('space', 'Không gian', 'medium', 4),
('spark', 'Tia lửa', 'medium', 4),
('spear', 'Ngọn giáo', 'medium', 4),
('spice', 'Gia vị', 'medium', 4),
('spine', 'Cột sống', 'medium', 4),
('spray', 'Phun / Xịt', 'medium', 4),
('squad', 'Đội', 'medium', 4),
('stage', 'Sân khấu', 'medium', 4),
('stain', 'Vết bẩn', 'medium', 4),
('stair', 'Bậc thang', 'medium', 4),
('stamp', 'Con tem', 'medium', 4),
('stare', 'Nhìn chằm chằm', 'medium', 4),
('steam', 'Hơi nước', 'medium', 4),
('steel', 'Thép', 'medium', 4),
('steep', 'Dốc', 'medium', 4),
('stork', 'Con cò', 'medium', 4),
('stove', 'Bếp lò', 'medium', 4),
('straw', 'Ống hút / Rơm', 'medium', 4),
('strip', 'Dải / Thanh', 'medium', 4),
('sugar', 'Đường', 'medium', 4),
('swamp', 'Đầm lầy', 'medium', 4),
('swing', 'Xích đu', 'medium', 4),
('sword', 'Thanh kiếm', 'medium', 4),
('syrup', 'Xi rô', 'medium', 4),
('thorn', 'Gai', 'medium', 4),
('toast', 'Bánh mì nướng', 'medium', 4),
('trunk', 'Thân cây', 'medium', 4),
('tulip', 'Hoa tulip', 'medium', 4),
('vault', 'Hầm', 'medium', 4),
('viper', 'Rắn lục', 'medium', 4),
('wheat', 'Lúa mì', 'medium', 4),
('wheel', 'Bánh xe', 'medium', 4),
('witch', 'Phù thủy', 'medium', 4),
('youth', 'Tuổi trẻ', 'medium', 4),
('zebra', 'Ngựa vằn', 'medium', 4),
-- 6 letters (medium, level 6)
('flower', 'Bông hoa', 'medium', 6),
('school', 'Trường học', 'medium', 6),
('friend', 'Bạn bè', 'medium', 6),
('family', 'Gia đình', 'medium', 6),
('orange', 'Quả cam', 'medium', 6),
('monkey', 'Con khỉ', 'medium', 6),
('rabbit', 'Con thỏ', 'medium', 6),
('mother', 'Mẹ', 'medium', 6),
('father', 'Bố', 'medium', 6),
('sister', 'Chị/em gái', 'medium', 6),
('garden', 'Khu vườn', 'medium', 6),
('winter', 'Mùa đông', 'medium', 6),
('summer', 'Mùa hè', 'medium', 6),
('banana', 'Quả chuối', 'medium', 6),
('planet', 'Hành tinh', 'medium', 6),
('parrot', 'Con vẹt', 'medium', 6),
('turtle', 'Con rùa', 'medium', 6),
('spider', 'Con nhện', 'medium', 6),
('insect', 'Côn trùng', 'medium', 6),
('kitten', 'Mèo con', 'medium', 6),
('puppy', 'Chó con', 'medium', 6),
('donkey', 'Con lừa', 'medium', 6),
('pigeon', 'Chim bồ câu', 'medium', 6),
('cherry', 'Quả anh đào', 'medium', 6),
('potato', 'Khoai tây', 'medium', 6),
('tomato', 'Cà chua', 'medium', 6),
('carrot', 'Cà rốt', 'medium', 6),
('pepper', 'Ớt / Tiêu', 'medium', 6),
('cheese', 'Phô mai', 'medium', 6),
('butter', 'Bơ', 'medium', 6),
('coffee', 'Cà phê', 'medium', 6),
('cookie', 'Bánh quy', 'medium', 6),
('noodle', 'Mì / Phở', 'medium', 6),
('dinner', 'Bữa tối', 'medium', 6),
('bottle', 'Chai / Lọ', 'medium', 6),
('basket', 'Cái rổ', 'medium', 6),
('bucket', 'Cái xô', 'medium', 6),
('mirror', 'Gương', 'medium', 6),
('pillow', 'Cái gối', 'medium', 6),
('window', 'Cửa sổ', 'medium', 6),
('candle', 'Cây nến', 'medium', 6),
('camera', 'Máy ảnh', 'medium', 6),
('guitar', 'Đàn ghi-ta', 'medium', 6),
('rocket', 'Tên lửa', 'medium', 6),
('bridge', 'Cây cầu', 'medium', 6),
('castle', 'Lâu đài', 'medium', 6),
('temple', 'Ngôi đền', 'medium', 6),
('market', 'Chợ', 'medium', 6),
('street', 'Đường phố', 'medium', 6),
('forest', 'Rừng', 'medium', 6),
('island', 'Hòn đảo', 'medium', 6),
('desert', 'Sa mạc', 'medium', 6),
('spring', 'Mùa xuân', 'medium', 6),
('autumn', 'Mùa thu', 'medium', 6),
('people', 'Mọi người', 'medium', 6),
('doctor', 'Bác sĩ', 'medium', 6),
('police', 'Cảnh sát', 'medium', 6),
('farmer', 'Nông dân', 'medium', 6),
('singer', 'Ca sĩ', 'medium', 6),
('driver', 'Tài xế', 'medium', 6),
('jacket', 'Áo khoác', 'medium', 6),
('sandal', 'Dép', 'medium', 6),
('gloves', 'Găng tay', 'medium', 6),
('tongue', 'Cái lưỡi', 'medium', 6),
('finger', 'Ngón tay', 'medium', 6),
('elbow', 'Khuỷu tay', 'medium', 6),
('muscle', 'Cơ bắp', 'medium', 6),
('silver', 'Bạc', 'medium', 6),
('yellow', 'Màu vàng', 'medium', 6),
('purple', 'Màu tím', 'medium', 6),
('circle', 'Hình tròn', 'medium', 6),
('square', 'Hình vuông', 'medium', 6),
('number', 'Con số', 'medium', 6),
('letter', 'Chữ cái', 'medium', 6),
('pencil', 'Bút chì', 'medium', 6),
('eraser', 'Cục tẩy', 'medium', 6),
('listen', 'Lắng nghe', 'medium', 6),
('travel', 'Du lịch', 'medium', 6),
('flying', 'Bay', 'medium', 6),
('frozen', 'Đông lạnh', 'medium', 6),
('hungry', 'Đói', 'medium', 6),
('thirst', 'Khát', 'medium', 6),
('strong', 'Mạnh mẽ', 'medium', 6),
('gentle', 'Dịu dàng', 'medium', 6),
('scared', 'Sợ hãi', 'medium', 6),
('cloudy', 'Nhiều mây', 'medium', 6),
('snowy', 'Có tuyết', 'medium', 6),
('stormy', 'Bão', 'medium', 6),
('sunny', 'Nắng', 'medium', 6),
('soccer', 'Bóng đá', 'medium', 6),
('tennis', 'Quần vợt', 'medium', 6),
('trophy', 'Cúp / Giải', 'medium', 6),
('anchor', 'Mỏ neo', 'medium', 6),
('badger', 'Con lửng', 'medium', 6),
('bakery', 'Tiệm bánh', 'medium', 6),
('ballet', 'Múa ba lê', 'medium', 6),
('bamboo', 'Tre', 'medium', 6),
('barber', 'Thợ cắt tóc', 'medium', 6),
('blanket', 'Chăn', 'medium', 6),
('bronze', 'Đồng', 'medium', 6),
('bubble', 'Bong bóng', 'medium', 6),
('cactus', 'Cây xương rồng', 'medium', 6),
('canyon', 'Hẻm núi', 'medium', 6),
('carpet', 'Thảm', 'medium', 6),
('cement', 'Xi măng', 'medium', 6),
('circus', 'Rạp xiếc', 'medium', 6),
('collar', 'Cổ áo', 'medium', 6),
('column', 'Cột', 'medium', 6),
('cotton', 'Bông / Vải', 'medium', 6),
('cuckoo', 'Chim cu cu', 'medium', 6),
('dolphin', 'Cá heo', 'medium', 6),
('dragon', 'Con rồng', 'medium', 6),
('falcon', 'Chim ưng', 'medium', 6),
('feather', 'Lông vũ', 'medium', 6),
('fossil', 'Hóa thạch', 'medium', 6),
('galaxy', 'Thiên hà', 'medium', 6),
('garlic', 'Tỏi', 'medium', 6),
('ginger', 'Gừng', 'medium', 6),
('harbor', 'Bến cảng', 'medium', 6),
('helmet', 'Mũ bảo hiểm', 'medium', 6),
('hobbit', 'Người lùn Hobbit', 'medium', 6),
('kettle', 'Ấm đun nước', 'medium', 6),
('knight', 'Hiệp sĩ', 'medium', 6),
('lizard', 'Con thằn lằn', 'medium', 6),
('locker', 'Tủ khóa', 'medium', 6),
('magnet', 'Nam châm', 'medium', 6),
('marble', 'Viên bi', 'medium', 6),
('needle', 'Cái kim', 'medium', 6),
('oyster', 'Con hàu', 'medium', 6),
('pickle', 'Dưa muối', 'medium', 6),
('pirate', 'Cướp biển', 'medium', 6),
('pocket', 'Túi áo', 'medium', 6),
('puzzle', 'Câu đố', 'medium', 6),
('shovel', 'Cái xẻng', 'medium', 6),
('statue', 'Bức tượng', 'medium', 6),
('sunset', 'Hoàng hôn', 'medium', 6),
('ticket', 'Vé', 'medium', 6),
('tissue', 'Khăn giấy', 'medium', 6),
-- 7+ letters (hard, level 8)
('kitchen', 'Nhà bếp', 'hard', 8),
('teacher', 'Giáo viên', 'hard', 8),
('picture', 'Bức tranh', 'hard', 8),
('chicken', 'Con gà', 'hard', 8),
('student', 'Học sinh', 'hard', 8),
('rainbow', 'Cầu vồng', 'hard', 8),
('morning', 'Buổi sáng', 'hard', 8),
('evening', 'Buổi tối', 'hard', 8),
('giraffe', 'Hươu cao cổ', 'hard', 8),
('penguin', 'Chim cánh cụt', 'hard', 8),
('octopus', 'Bạch tuộc', 'hard', 8),
('lobster', 'Tôm hùm', 'hard', 8),
('hamster', 'Chuột hamster', 'hard', 8),
('panther', 'Báo đen', 'hard', 8),
('buffalo', 'Con trâu', 'hard', 8),
('sparrow', 'Chim sẻ', 'hard', 8),
('peacock', 'Con công', 'hard', 8),
('leopard', 'Con báo', 'hard', 8),
('monster', 'Quái vật', 'hard', 8),
('diamond', 'Kim cương', 'hard', 8),
('volcano', 'Núi lửa', 'hard', 8),
('weather', 'Thời tiết', 'hard', 8),
('thunder', 'Sấm sét', 'hard', 8),
('country', 'Đất nước', 'hard', 8),
('village', 'Ngôi làng', 'hard', 8),
('library', 'Thư viện', 'hard', 8),
('airport', 'Sân bay', 'hard', 8),
('stadium', 'Sân vận động', 'hard', 8),
('hospital', 'Bệnh viện', 'hard', 8),
('bedroom', 'Phòng ngủ', 'hard', 8),
('bathroom', 'Phòng tắm', 'hard', 8),
('umbrella', 'Cái ô / Dù', 'hard', 8),
('backpack', 'Ba lô', 'hard', 8),
('necklace', 'Vòng cổ', 'hard', 8),
('bracelet', 'Vòng tay', 'hard', 8),
('sandwich', 'Bánh mì kẹp', 'hard', 8),
('pancake', 'Bánh kếp', 'hard', 8),
('popcorn', 'Bỏng ngô', 'hard', 8),
('pumpkin', 'Bí ngô', 'hard', 8),
('cabbage', 'Bắp cải', 'hard', 8),
('avocado', 'Quả bơ', 'hard', 8),
('coconut', 'Quả dừa', 'hard', 8),
('pineapple', 'Quả dứa', 'hard', 8),
('blueberry', 'Quả việt quất', 'hard', 8),
('strawberry', 'Quả dâu tây', 'hard', 8),
('watermelon', 'Quả dưa hấu', 'hard', 8),
('chocolate', 'Sô cô la', 'hard', 8),
('spaghetti', 'Mì Ý', 'hard', 8),
('hamburger', 'Bánh hamburger', 'hard', 8),
('breakfast', 'Bữa sáng', 'hard', 8),
('scissors', 'Cái kéo', 'hard', 8),
('calendar', 'Lịch', 'hard', 8),
('computer', 'Máy tính', 'hard', 8),
('notebook', 'Vở / Sổ tay', 'hard', 8),
('textbook', 'Sách giáo khoa', 'hard', 8),
('magazine', 'Tạp chí', 'hard', 8),
('birthday', 'Sinh nhật', 'hard', 8),
('holiday', 'Ngày lễ', 'hard', 8),
('weekend', 'Cuối tuần', 'hard', 8),
('tonight', 'Tối nay', 'hard', 8),
('sunlight', 'Ánh nắng', 'hard', 8),
('moonlight', 'Ánh trăng', 'hard', 8),
('mountain', 'Ngọn núi', 'hard', 8),
('waterfall', 'Thác nước', 'hard', 8),
('mushroom', 'Nấm', 'hard', 8),
('treasure', 'Kho báu', 'hard', 8),
('princess', 'Công chúa', 'hard', 8),
('soldier', 'Người lính', 'hard', 8),
('captain', 'Thuyền trưởng', 'hard', 8),
('painter', 'Họa sĩ', 'hard', 8),
('dentist', 'Nha sĩ', 'hard', 8),
('fireman', 'Lính cứu hỏa', 'hard', 8),
('brother', 'Anh/em trai', 'hard', 8),
('grandma', 'Bà', 'hard', 8),
('grandpa', 'Ông', 'hard', 8),
('husband', 'Chồng', 'hard', 8),
('neighbor', 'Hàng xóm', 'hard', 8),
('shoulder', 'Vai', 'hard', 8),
('stomach', 'Bụng / Dạ dày', 'hard', 8),
('elephant', 'Con voi', 'hard', 8),
('squirrel', 'Con sóc', 'hard', 8),
('kangaroo', 'Chuột túi', 'hard', 8),
('flamingo', 'Hồng hạc', 'hard', 8),
('goldfish', 'Cá vàng', 'hard', 8),
('starfish', 'Sao biển', 'hard', 8),
('butterfly', 'Con bướm', 'hard', 8),
('jellyfish', 'Con sứa', 'hard', 8),
('crocodile', 'Cá sấu', 'hard', 8),
('dragonfly', 'Chuồn chuồn', 'hard', 8),
('sunflower', 'Hoa hướng dương', 'hard', 8),
('classroom', 'Lớp học', 'hard', 8),
('building', 'Tòa nhà', 'hard', 8),
('playground', 'Sân chơi', 'hard', 8),
('universe', 'Vũ trụ', 'hard', 8),
('triangle', 'Hình tam giác', 'hard', 8),
('rectangle', 'Hình chữ nhật', 'hard', 8),
('question', 'Câu hỏi', 'hard', 8),
('language', 'Ngôn ngữ', 'hard', 8),
('alphabet', 'Bảng chữ cái', 'hard', 8),
('painting', 'Bức tranh', 'hard', 8),
('exercise', 'Bài tập', 'hard', 8),
('swimming', 'Bơi lội', 'hard', 8),
('running', 'Chạy bộ', 'hard', 8),
('sleeping', 'Đang ngủ', 'hard', 8),
('shopping', 'Mua sắm', 'hard', 8),
('champion', 'Nhà vô địch', 'hard', 8),
('dinosaur', 'Khủng long', 'hard', 8),
('address', 'Địa chỉ', 'hard', 8),
('balcony', 'Ban công', 'hard', 8),
('battery', 'Pin', 'hard', 8),
('cabinet', 'Tủ', 'hard', 8),
('ceiling', 'Trần nhà', 'hard', 8),
('century', 'Thế kỷ', 'hard', 8),
('chapter', 'Chương', 'hard', 8),
('concert', 'Buổi hòa nhạc', 'hard', 8),
('dessert', 'Món tráng miệng', 'hard', 8),
('display', 'Màn hình', 'hard', 8),
('factory', 'Nhà máy', 'hard', 8),
('pajamas', 'Đồ ngủ', 'hard', 8),
('parking', 'Bãi đỗ xe', 'hard', 8),
('pyramid', 'Kim tự tháp', 'hard', 8),
('reindeer', 'Tuần lộc', 'hard', 8),
('rooster', 'Gà trống', 'hard', 8),
('seagull', 'Chim hải âu', 'hard', 8),
('shrimp', 'Con tôm', 'hard', 8),
('silence', 'Sự im lặng', 'hard', 8),
('skating', 'Trượt băng', 'hard', 8),
('snowman', 'Người tuyết', 'hard', 8),
('tornado', 'Lốc xoáy', 'hard', 8),
('tourist', 'Du khách', 'hard', 8),
('unicorn', 'Kỳ lân', 'hard', 8),
('uniform', 'Đồng phục', 'hard', 8),
('vampire', 'Ma cà rồng', 'hard', 8),
('vanilla', 'Vani', 'hard', 8),
('vinegar', 'Giấm', 'hard', 8),
('aquarium', 'Bể cá', 'hard', 8),
('cucumber', 'Dưa chuột', 'hard', 8),
('firework', 'Pháo hoa', 'hard', 8),
('furniture', 'Đồ nội thất', 'hard', 8),
('gentleman', 'Quý ông', 'hard', 8),
('geography', 'Địa lý', 'hard', 8)
ON CONFLICT (word) DO NOTHING;
